from __future__ import annotations

import re
from dataclasses import dataclass

from training_cards.philosophy_profiles import MAINSTREAM_ENDURANCE
from training_cards.schemas import CardRelationship, CardReference, CardType, MicroCard, TrainingLevel


@dataclass(frozen=True, slots=True)
class _MicroSpec:
    id: str
    title: str
    parent_mezzo_id: str
    parent_title: str
    parent_tag: str
    summary_action: str
    purpose_action: str
    emphasis: str
    avoid: str
    key_sessions: list[str]
    load_pattern: str
    trail_context: str


def _slugify(value: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")
    return f"mainstream-{slug}"


def _parent(mezzo_id: str, tag: str) -> list[CardReference]:
    return [CardReference(card_id=mezzo_id, relationship=CardRelationship.PARENT, tags=[tag])]


def _mainstream_micro(spec: _MicroSpec) -> MicroCard:
    return MicroCard(
        id=spec.id,
        slug=_slugify(spec.title),
        title=spec.title,
        card_type=CardType.MICRO,
        suitable_levels=[TrainingLevel.ALL],
        philosophy_profile_ids=[MAINSTREAM_ENDURANCE],
        summary=f"A mainstream week structure that {spec.summary_action}.",
        purpose=f"Organize one week inside the {spec.parent_title} so the athlete can {spec.purpose_action}.",
        tags=["mainstream_endurance", "micro", spec.parent_tag, *(_slugify(spec.title).split("-")[1:])],
        goal_race_context=[
            f"Use inside the {spec.parent_title}.",
            "Fits when the athlete needs a reusable weekly structure rather than a single workout prescription.",
            "Select this week only when its main job matches the current block and athlete readiness.",
        ],
        training_profile=[
            spec.emphasis,
            f"Load pattern: {spec.load_pattern}",
            spec.trail_context,
        ],
        expected_adaptations=[
            "Clearer weekly stress distribution.",
            "Better connection between the parent block purpose and day-to-day training choices.",
            "More reliable progression because recovery and readiness are visible across the week.",
        ],
        watchouts=[
            spec.avoid,
            "Do not turn this micro card into an exact calendar before athlete constraints and recovery are known.",
            "Avoid adding extra hard work just because the week feels well organised.",
        ],
        progression_rules=[
            "Progress only one main variable at a time: frequency, duration, intensity, vertical load, technicality, or density.",
            "Repeat the same week type when adaptation is still useful and recovery remains predictable.",
            "Move to a more demanding week type only when the athlete finishes the week with stable soreness, mood, sleep, and easy-effort feel.",
        ],
        regression_rules=[
            "Reduce load, terrain cost, or session density if recovery signals worsen.",
            "Use an easier or absorption-oriented week when soreness, motivation, sleep, or easy pace/effort disconnects from normal.",
            "Return to the parent block's simpler week type if the current structure creates avoidable complexity.",
        ],
        additional_information=(
            "This card defines a reusable week role, not a fixed seven-day schedule. "
            "The coach should choose exact sessions, rest days, terrain, and progression from the athlete's context while preserving the week job."
        ),
        references=_parent(spec.parent_mezzo_id, spec.parent_tag),
        recommended_duration_days="7",
        week_structure=[
            "Anchor the week around one clear coaching job.",
            "Place key work where the athlete can execute it well.",
            "Use the remaining days to support the week's purpose through easy running, rest, mobility, or low-cost aerobic work.",
        ],
        key_sessions=spec.key_sessions,
        load_pattern=spec.load_pattern,
        placement_guidance=[
            f"Place within the {spec.parent_title} when this week role matches the block sequence.",
            "Repeat, progress, or alternate with a lower-cost week according to athlete response.",
        ],
        recovery_requirements=[
            "At least one clear recovery opportunity before or after the highest-cost session.",
            "Easy days must stay easy enough to preserve the week purpose.",
            "Adjust quickly if soreness, sleep, mood, motivation, or easy-effort feel trends in the wrong direction.",
        ],
    )


_SPECS: tuple[_MicroSpec, ...] = (
    _MicroSpec(
        "micro_001",
        "Routine Anchor Week",
        "mezzo_001",
        "Re-Entry Rhythm Block",
        "reentry_rhythm",
        "rebuilds a dependable training rhythm with short, easy, predictable exposures",
        "make running feel repeatable again before meaningful load progression",
        "Short easy runs, run-walks, or walks are placed with enough spacing that the athlete finishes the week confident rather than tested.",
        "Avoid chasing previous fitness, adding technical terrain, or filling every available day with training.",
        ["Short easy run or run-walk", "Optional walk or mobility day", "Rest day used deliberately"],
        "Very low load, low density, and high predictability.",
        "Trail exposure should stay smooth, familiar, and low consequence if used at all.",
    ),
    _MicroSpec(
        "micro_002",
        "Frequency Extension Week",
        "mezzo_001",
        "Re-Entry Rhythm Block",
        "reentry_rhythm",
        "adds one small weekly exposure after basic rhythm is stable",
        "extend frequency without turning re-entry into a fitness test",
        "The week adds a small session or slightly lengthens one easy outing while keeping intensity and terrain simple.",
        "Avoid adding both frequency and duration aggressively in the same week.",
        ["Short easy run", "Very short optional aerobic exposure", "Rest or mobility support"],
        "Low load with one small progression in frequency or duration.",
        "Use flat or forgiving trails only when they do not add hidden mechanical cost.",
    ),
    _MicroSpec(
        "micro_003",
        "Easy Aerobic Reconditioning Week",
        "mezzo_002",
        "Easy Aerobic Reconditioning Block",
        "easy_aerobic_reconditioning",
        "rebuilds basic easy aerobic tolerance without rushing normal training load",
        "restore easy endurance and confidence after interruption",
        "Most training is easy aerobic work at a dose the athlete can repeat without strain.",
        "Avoid using steady effort to make the week feel more productive.",
        ["Easy aerobic run", "Optional low-impact aerobic session", "Short recovery run or walk"],
        "Low-to-moderate easy volume with conservative progression.",
        "Trail terrain should be familiar and controlled; measure effort by time and recovery, not pace.",
    ),
    _MicroSpec(
        "micro_004",
        "Aerobic Reconditioning Hold Week",
        "mezzo_002",
        "Easy Aerobic Reconditioning Block",
        "easy_aerobic_reconditioning",
        "holds easy aerobic work steady so returning fitness can settle",
        "consolidate reconditioning before another increase",
        "The week repeats a known easy load and watches tissue response, mood, and easy-effort feel.",
        "Avoid interpreting a hold week as failure or adding intensity because volume is unchanged.",
        ["Repeatable easy aerobic run", "Low-cost cross-training option", "Rest or mobility day"],
        "Stable easy load with no meaningful progression.",
        "Keep vertical gain and descent cost similar to the prior successful week.",
    ),
    _MicroSpec(
        "micro_005",
        "Strength Reintroduction Week",
        "mezzo_003",
        "Movement Strength Reintroduction Block",
        "movement_strength_reintroduction",
        "reintroduces simple strength and movement work without disrupting easy running",
        "restore movement confidence and low-risk durability support",
        "Strength, mobility, drills, or strides return at a small dose with careful spacing around runs.",
        "Avoid soreness-heavy strength, new plyometrics, or stacking strength before key running days.",
        ["Simple strength session", "Easy run", "Mobility or drill support"],
        "Low running load with very low-to-low strength novelty.",
        "Downhill and technical terrain should be limited until soreness response is predictable.",
    ),
    _MicroSpec(
        "micro_006",
        "Movement Tolerance Check Week",
        "mezzo_003",
        "Movement Strength Reintroduction Block",
        "movement_strength_reintroduction",
        "checks soreness and coordination after reintroduced movement work",
        "decide whether movement support is ready to progress or should stay simple",
        "The week keeps movement support present while checking next-day stiffness, coordination, and easy-running quality.",
        "Avoid progressing strength if running mechanics or soreness worsen.",
        ["Low-dose strength session", "Easy run after strength", "Mobility and tissue-care support"],
        "Low-to-moderate support load with response monitoring.",
        "Use gentle trail exposure only if descents and uneven footing do not amplify soreness.",
    ),
    _MicroSpec(
        "micro_007",
        "Aerobic Volume Baseline Week",
        "mezzo_004",
        "Aerobic Volume Block",
        "aerobic_volume",
        "establishes the athlete's current repeatable easy volume",
        "confirm the weekly aerobic baseline before building",
        "The week identifies a sustainable mix of frequency and duration that does not require heroic recovery.",
        "Avoid building from a week that was barely survived.",
        ["Easy aerobic run", "Longer easy run if already familiar", "Recovery run or rest day"],
        "Moderate easy load held at a known sustainable level.",
        "Trail time should reflect ordinary terrain, not an unusually costly adventure week.",
    ),
    _MicroSpec(
        "micro_008",
        "Aerobic Volume Build Week",
        "mezzo_004",
        "Aerobic Volume Block",
        "aerobic_volume",
        "builds weekly easy aerobic load through frequency or duration",
        "increase aerobic volume while preserving easy effort and repeatability",
        "The week grows easy running through one main variable while keeping intensity controlled.",
        "Avoid turning volume progression into faster everyday running.",
        ["Easy aerobic run", "Longer easy run", "Recovery run"],
        "Moderate easy load with one controlled progression.",
        "Use time, vertical cost, and descent soreness when trail distance is a poor load guide.",
    ),
    _MicroSpec(
        "micro_009",
        "Aerobic Volume Absorption Week",
        "mezzo_004",
        "Aerobic Volume Block",
        "aerobic_volume",
        "consolidates recent aerobic volume before the next build",
        "absorb frequency and duration so aerobic development remains durable",
        "The week holds or slightly reduces easy volume and protects recovery without abandoning routine.",
        "Avoid sneaking in intensity because the week feels less ambitious.",
        ["Short easy run", "Normal easy run", "Rest or low-impact aerobic day"],
        "Slightly reduced or stable easy load.",
        "Keep terrain familiar and lower the descent or technical cost if fatigue is lingering.",
    ),
    _MicroSpec(
        "micro_010",
        "Long Run Extension Week",
        "mezzo_005",
        "Long Endurance Development Block",
        "long_endurance_development",
        "extends the long-endurance stimulus while the rest of the week supports recovery",
        "develop longer-duration tolerance without making the long run a weekly exam",
        "The long outing is the main stress, and other sessions are arranged to protect its execution and recovery.",
        "Avoid extending the long run while also increasing intensity, terrain novelty, and weekly volume.",
        ["Long easy run or time-on-feet outing", "Easy aerobic support run", "Recovery day"],
        "Moderate-to-high single-session cost with supportive surrounding load.",
        "Trail goals may use time, climbing, hiking, and descent tolerance instead of distance.",
    ),
    _MicroSpec(
        "micro_011",
        "Long Endurance Specificity Week",
        "mezzo_005",
        "Long Endurance Development Block",
        "long_endurance_development",
        "changes the long-endurance context toward the athlete's goal demands",
        "practice the kind of endurance the goal will require",
        "The week keeps endurance primary but adjusts terrain, duration, fueling, hiking, or vertical demand toward the target context.",
        "Avoid making every specific long week a full race simulation.",
        ["Goal-relevant long outing", "Fueling or hiking practice", "Easy recovery run"],
        "Moderate-to-high endurance load with one specific demand emphasized.",
        "Choose the trail demand that matters most: climb, descent, footing, duration, remoteness, or heat.",
    ),
    _MicroSpec(
        "micro_012",
        "Long Run Consolidation Week",
        "mezzo_005",
        "Long Endurance Development Block",
        "long_endurance_development",
        "repeats or slightly eases long-endurance work so adaptation can settle",
        "stabilize long-run tolerance before another extension or specificity increase",
        "The week keeps a familiar long outing while reducing novelty, density, or total cost elsewhere.",
        "Avoid using consolidation as an excuse for another bigger long run.",
        ["Familiar long easy run", "Short recovery run", "Rest or mobility support"],
        "Stable long-run cost with reduced novelty and supportive easy volume.",
        "Use familiar terrain and avoid aggressive descents if muscle damage is still present.",
    ),
    _MicroSpec(
        "micro_013",
        "Strength Support Integration Week",
        "mezzo_006",
        "Strength And Movement Support Block",
        "strength_movement_support",
        "integrates strength support into the week without stealing from running",
        "improve durability support while preserving the parent training goal",
        "Strength or movement work is placed so it supports rather than competes with key running.",
        "Avoid loading strength so heavily that easy runs become compromised.",
        ["Strength support session", "Easy aerobic run", "Mobility or drill session"],
        "Low-to-moderate support load carefully spaced around running.",
        "Downhill-heavy trail weeks may need lighter strength placement or reduced eccentric load.",
    ),
    _MicroSpec(
        "micro_014",
        "Strength Support Deload Week",
        "mezzo_006",
        "Strength And Movement Support Block",
        "strength_movement_support",
        "reduces strength cost while preserving movement quality",
        "let support work absorb when running or life stress needs priority",
        "The week lowers strength load, novelty, or volume while keeping useful mobility and activation present.",
        "Avoid dropping all movement support if a small dose would help the week stay organised.",
        ["Light strength or activation", "Easy run", "Mobility support"],
        "Reduced support load with normal or simplified easy running.",
        "Use deloading especially when trails add downhill, unstable footing, or climbing fatigue.",
    ),
    _MicroSpec(
        "micro_015",
        "Trail Familiarity Exposure Week",
        "mezzo_028",
        "Trail Skill And Terrain Familiarity Block",
        "trail_skill_terrain",
        "adds controlled trail or terrain exposure without turning the week race-specific",
        "build confidence and coordination on relevant terrain",
        "The week introduces terrain, gradient, or surface demands at low-to-moderate cost.",
        "Avoid combining technical novelty with high fatigue or long descents too soon.",
        ["Controlled trail run", "Easy aerobic support run", "Skill-focused strides or drills"],
        "Low-to-moderate aerobic load with controlled terrain novelty.",
        "Select terrain that teaches the athlete without punishing them.",
    ),
    _MicroSpec(
        "micro_016",
        "Trail Skill Consolidation Week",
        "mezzo_028",
        "Trail Skill And Terrain Familiarity Block",
        "trail_skill_terrain",
        "repeats familiar trail demands until movement becomes more fluent",
        "stabilize trail confidence before adding more difficulty",
        "The week uses familiar terrain and simple session structure so coordination improves without excess fatigue.",
        "Avoid escalating technicality whenever confidence improves.",
        ["Familiar trail run", "Easy run on forgiving surface", "Mobility or balance support"],
        "Stable low-to-moderate load with repeated terrain exposure.",
        "Keep descent cost and technical challenge similar to recently successful weeks.",
    ),
    _MicroSpec(
        "micro_017",
        "Threshold Introduction Week",
        "mezzo_007",
        "Threshold Control Block",
        "threshold_control",
        "introduces controlled threshold work with enough easy support",
        "teach comfortably-hard restraint before larger threshold doses",
        "One controlled threshold touch is placed in an otherwise easy and recoverable week.",
        "Avoid drifting from controlled threshold into race effort.",
        ["Controlled threshold session", "Easy aerobic run", "Recovery run"],
        "Moderate quality load with generous easy support.",
        "Use steady terrain where effort can be controlled; climbs may be useful if they do not distort intensity.",
    ),
    _MicroSpec(
        "micro_018",
        "Threshold Development Week",
        "mezzo_007",
        "Threshold Control Block",
        "threshold_control",
        "develops threshold capacity while preserving weekly recovery",
        "increase threshold dose or specificity without losing control",
        "The week builds threshold volume, duration, or terrain relevance while keeping the rest of training supportive.",
        "Avoid stacking multiple moderate-hard days until the whole week becomes grey-zone work.",
        ["Threshold development session", "Easy aerobic support run", "Long easy run if appropriate"],
        "Moderate-to-high quality emphasis with controlled surrounding load.",
        "Trail threshold work should be effort-governed because pace may be misleading.",
    ),
    _MicroSpec(
        "micro_019",
        "Threshold Absorption Week",
        "mezzo_007",
        "Threshold Control Block",
        "threshold_control",
        "simplifies threshold demand so the athlete can absorb the work",
        "check whether controlled quality is creating adaptation or fatigue",
        "The week reduces threshold volume, complexity, or terrain cost while maintaining easy rhythm.",
        "Avoid interpreting fatigue as a reason to squeeze in one more threshold session before resting.",
        ["Short threshold touch or no quality", "Easy aerobic run", "Recovery run or rest day"],
        "Reduced quality load with preserved easy frequency.",
        "Use flatter or less technical terrain if prior quality created musculoskeletal fatigue.",
    ),
    _MicroSpec(
        "micro_020",
        "Aerobic Power Introduction Week",
        "mezzo_008",
        "Aerobic Power Block",
        "aerobic_power",
        "introduces aerobic-power work conservatively",
        "prepare the athlete for high-end aerobic stress without an abrupt jump",
        "The week uses a small aerobic-power dose with familiar terrain and clear recovery spacing.",
        "Avoid pairing new high-intensity work with new technical or downhill stress.",
        ["Short aerobic-power intervals", "Easy aerobic run", "Recovery day"],
        "Moderate quality load with low novelty and strong recovery spacing.",
        "Choose terrain that allows clean mechanics and safe control before using trails for power work.",
    ),
    _MicroSpec(
        "micro_021",
        "Aerobic Power Stimulus Week",
        "mezzo_008",
        "Aerobic Power Block",
        "aerobic_power",
        "places a clear aerobic-power stimulus into a supportive week",
        "develop high-end aerobic capacity without stacking too many hard demands",
        "The week includes one meaningful aerobic-power session and protects the days around it.",
        "Avoid adding a second hard session unless the athlete has already proven recovery from this pattern.",
        ["Aerobic-power interval session", "Easy aerobic support run", "Long easy run or recovery run"],
        "High-quality focal stimulus with otherwise easy support.",
        "Trail versions should protect footing and descent cost so the power stimulus stays the main stress.",
    ),
    _MicroSpec(
        "micro_022",
        "Aerobic Power Recovery-Spacing Week",
        "mezzo_008",
        "Aerobic Power Block",
        "aerobic_power",
        "keeps power work recoverable through spacing and reduced complexity",
        "absorb aerobic-power stress without losing the block signal",
        "The week preserves a small quality signal while increasing recovery space or lowering volume.",
        "Avoid treating recovery spacing as optional after demanding aerobic-power work.",
        ["Small aerobic-power touch", "Easy run", "Rest or low-impact aerobic day"],
        "Reduced or spaced quality load with protective easy days.",
        "Simplify terrain when technical trails would add neuromuscular cost.",
    ),
    _MicroSpec(
        "micro_023",
        "Strength Endurance Introduction Week",
        "mezzo_009",
        "Strength Endurance Block",
        "strength_endurance",
        "introduces sustained muscular demand before fuller strength-endurance work",
        "prepare tissue and pacing for uphill or resisted endurance stress",
        "The week adds a small muscular-endurance stimulus while watching soreness and easy-running quality.",
        "Avoid jumping straight to long steep climbs, heavy load, or hard descents.",
        ["Short uphill endurance session", "Easy aerobic run", "Strength or mobility support"],
        "Moderate muscular load with conservative duration and recovery spacing.",
        "Use grade and footing that create the intended stress without excessive downhill damage.",
    ),
    _MicroSpec(
        "micro_024",
        "Strength Endurance Stimulus Week",
        "mezzo_009",
        "Strength Endurance Block",
        "strength_endurance",
        "creates a meaningful uphill, resistance, or muscular-endurance stimulus",
        "develop fatigue resistance for sustained force production",
        "The week centers one strength-endurance session and keeps other training supportive.",
        "Avoid increasing climb duration, steepness, load, and total weekly volume at the same time.",
        ["Strength-endurance climb session", "Easy aerobic run", "Recovery run or hike"],
        "Moderate-to-high muscular load with supportive aerobic volume.",
        "Track descent cost separately from climbing because soreness may come later.",
    ),
    _MicroSpec(
        "micro_025",
        "Strength Endurance Absorption Week",
        "mezzo_009",
        "Strength Endurance Block",
        "strength_endurance",
        "protects recovery after muscular-endurance stress",
        "let strength-endurance adaptation settle before another heavy dose",
        "The week reduces muscular load while preserving easy rhythm and checking residual soreness.",
        "Avoid using delayed soreness as background noise; it is a real load signal.",
        ["Easy aerobic run", "Gentle hike or mobility", "Optional short hill touch only if recovered"],
        "Reduced muscular load with low technical and downhill cost.",
        "Choose gentle terrain and avoid long descents if eccentric soreness remains.",
    ),
    _MicroSpec(
        "micro_026",
        "Course Demands Exposure Week",
        "mezzo_010",
        "Course Demands Block",
        "course_demands",
        "introduces one consequential goal-course demand in controlled form",
        "start preparing for the demands that will actually matter",
        "The week emphasizes one course demand such as vertical, surface, heat, technicality, duration, or hiking.",
        "Avoid copying the race just because the terrain is available.",
        ["Course-relevant exposure run", "Easy aerobic support run", "Recovery day"],
        "Moderate specific load with one clear demand emphasized.",
        "Pick the trail variable that changes the race most, not the one that looks most dramatic.",
    ),
    _MicroSpec(
        "micro_027",
        "Course Demands Integration Week",
        "mezzo_010",
        "Course Demands Block",
        "course_demands",
        "integrates course-specific work into normal training rhythm",
        "absorb specificity without losing the broader plan",
        "The week combines a relevant course demand with normal easy running and recovery structure.",
        "Avoid letting specificity crowd out recovery, aerobic support, or strength maintenance.",
        ["Goal-terrain run", "Easy aerobic support run", "Recovery or mobility day"],
        "Moderate-to-high specific load balanced by supportive easy days.",
        "Account for vertical, descent, footing, heat, and travel as real weekly load.",
    ),
    _MicroSpec(
        "micro_028",
        "Course Demands Simulation Week",
        "mezzo_010",
        "Course Demands Block",
        "course_demands",
        "tests multiple goal-course demands together when timing and readiness justify it",
        "practice integrated specificity without replacing the race",
        "The week uses a larger or more complete specific exposure while simplifying the rest of the week.",
        "Avoid using simulation to prove fitness too often or too close to the race.",
        ["Race-like terrain outing", "Fueling or gear practice", "Recovery run or rest day"],
        "High specific cost with reduced surrounding load.",
        "Simulation should include only the demands the athlete is ready to absorb.",
    ),
    _MicroSpec(
        "micro_029",
        "Race Execution Integration Week",
        "mezzo_011",
        "Race Execution Practice Block",
        "race_execution_practice",
        "introduces race-execution skills inside ordinary training",
        "make pacing, gear, fueling, and decision skills habitual before rehearsal",
        "The week adds one or two execution skills to normal sessions at low extra cost.",
        "Avoid saving all execution practice for one big rehearsal.",
        ["Easy run with pacing cues", "Gear or aid-flow practice", "Long easy run"],
        "Normal-to-moderate load with low extra execution complexity.",
        "Trail context may focus on hiking transitions, poles, technical pacing, or descent control.",
    ),
    _MicroSpec(
        "micro_030",
        "Race Execution Rehearsal Week",
        "mezzo_011",
        "Race Execution Practice Block",
        "race_execution_practice",
        "rehearses race execution in a structured but bounded week",
        "practice coordinated pacing, gear, terrain, fueling, and decision routines",
        "The week centers a rehearsal session and reduces other complexity so learning is clear.",
        "Avoid turning rehearsal into a race or adding too many new variables.",
        ["Race-execution rehearsal", "Easy support run", "Recovery day"],
        "Moderate-to-high rehearsal cost with simplified surrounding load.",
        "Use representative terrain when possible, but preserve safety and recovery.",
    ),
    _MicroSpec(
        "micro_031",
        "Execution Feedback Week",
        "mezzo_011",
        "Race Execution Practice Block",
        "race_execution_practice",
        "uses lower-cost training to convert rehearsal feedback into better choices",
        "adjust race strategy without overcorrecting everything at once",
        "The week keeps training simple and applies one clear lesson from prior execution practice.",
        "Avoid changing pacing, gear, nutrition, and terrain strategy all in the same week.",
        ["Easy run with one execution cue", "Short rehearsal touch", "Recovery support"],
        "Low-to-moderate load with one learning focus.",
        "Trail learning should focus on the variable that caused the biggest execution problem.",
    ),
    _MicroSpec(
        "micro_032",
        "Fueling Integration Week",
        "mezzo_012",
        "Fueling And Hydration Practice Block",
        "fueling_hydration_practice",
        "introduces fueling and hydration habits into ordinary endurance training",
        "make nutrition practice normal before it becomes a major rehearsal demand",
        "The week includes simple planned fueling or hydration in appropriate sessions.",
        "Avoid waiting until very long or very specific sessions to begin fueling practice.",
        ["Easy run with fueling habit", "Long easy run with planned intake", "Hydration check"],
        "Normal training load with low execution complexity.",
        "Heat, altitude, and long climbs may change fluid needs even when pace is easy.",
    ),
    _MicroSpec(
        "micro_033",
        "Fueling Practice Week",
        "mezzo_012",
        "Fueling And Hydration Practice Block",
        "fueling_hydration_practice",
        "practices fueling and hydration under realistic training stress",
        "improve nutrition execution during longer or race-relevant work",
        "The week places fueling practice into sessions long or specific enough to teach useful lessons.",
        "Avoid making the physical training too hard to interpret fueling response.",
        ["Long run fueling practice", "Race-relevant hydration practice", "Easy recovery run"],
        "Moderate-to-high endurance or specificity load with planned intake practice.",
        "Trail sessions should include carrying, access, aid timing, and gut comfort under terrain stress.",
    ),
    _MicroSpec(
        "micro_034",
        "Fueling Tolerance Check Week",
        "mezzo_012",
        "Fueling And Hydration Practice Block",
        "fueling_hydration_practice",
        "checks gut tolerance and logistics while physical stress stays controlled",
        "separate nutrition reliability from bigger fitness stress",
        "The week simplifies training enough to observe product choice, timing, heat response, and digestion.",
        "Avoid blaming fitness or effort when the real issue is fueling tolerance.",
        ["Controlled fueling test", "Easy aerobic run", "Recovery support"],
        "Low-to-moderate physical load with focused nutrition testing.",
        "Use terrain and conditions that match the likely race problem without adding unnecessary risk.",
    ),
    _MicroSpec(
        "micro_035",
        "Taper Load Reduction Week",
        "mezzo_013",
        "Taper Freshness Block",
        "taper_freshness",
        "reduces training cost while preserving rhythm and confidence",
        "start shedding fatigue without erasing familiar movement",
        "The week lowers volume, density, or long-run cost while keeping easy rhythm and possibly a small familiar touch.",
        "Avoid chasing new fitness once freshness is the priority.",
        ["Short easy run", "Small familiar quality touch", "Rest or mobility day"],
        "Reduced total load with preserved frequency where useful.",
        "Avoid downhill-heavy or technical novelty because muscle damage can linger into race week.",
    ),
    _MicroSpec(
        "micro_036",
        "Final Freshness Week",
        "mezzo_013",
        "Taper Freshness Block",
        "taper_freshness",
        "organizes the final pre-race week around freshness and familiarity",
        "arrive rested, calm, and ready without last-minute training noise",
        "The week uses short familiar movement, rest, logistics, and confidence-preserving routines.",
        "Avoid last-minute tests, new shoes, new terrain, or extra climbing to calm nerves.",
        ["Short easy run", "Brief familiar strides if appropriate", "Rest and logistics support"],
        "Very reduced load with low novelty and high recovery priority.",
        "Trail and ultra races may require travel, gear, pole, pack, and foot-care checks to shape the week.",
    ),
    _MicroSpec(
        "micro_037",
        "Sharpening Touchpoint Week",
        "mezzo_014",
        "Sharpening Touchpoint Block",
        "sharpening_touchpoint",
        "keeps a small familiar performance signal without creating fatigue",
        "preserve coordination and confidence late in preparation",
        "The week includes one small controlled quality touch while total training cost remains low.",
        "Avoid turning sharpening into a hidden workout block.",
        ["Short sharpening touch", "Easy aerobic run", "Recovery day"],
        "Low-to-moderate intensity touch with reduced overall load.",
        "Use terrain that feels familiar and safe; avoid technical risk close to the goal.",
    ),
    _MicroSpec(
        "micro_038",
        "Sharpening Absorption Week",
        "mezzo_014",
        "Sharpening Touchpoint Block",
        "sharpening_touchpoint",
        "lets a sharpening touch settle without inviting extra work",
        "protect freshness and confidence after late preparation quality",
        "The week keeps movement easy and familiar while resisting the urge to repeat successful sharpening.",
        "Avoid adding more sharp work because the previous touch felt good.",
        ["Easy run", "Brief strides only if useful", "Rest or mobility day"],
        "Reduced load with little or no additional quality.",
        "Keep terrain controlled and avoid downhill soreness close to racing.",
    ),
    _MicroSpec(
        "micro_039",
        "Readiness Confirmation Week",
        "mezzo_015",
        "Race Readiness Check Block",
        "race_readiness_check",
        "confirms readiness details with very low added cost",
        "verify logistics, gear, pacing cues, fueling, and body signals without testing fitness",
        "The week integrates readiness checks into short familiar movement and simple routines.",
        "Avoid letting checklists become stressful or physically costly.",
        ["Short easy run", "Gear or fueling check", "Brief familiar cue practice"],
        "Very low training cost with high logistical clarity.",
        "Trail goals may require pack, shoes, poles, lighting, weather, and aid-access checks.",
    ),
    _MicroSpec(
        "micro_040",
        "Pre-Race Settle Week",
        "mezzo_015",
        "Race Readiness Check Block",
        "race_readiness_check",
        "prioritizes calm and familiar movement when the race is very near",
        "reduce noise and protect confidence before the goal",
        "The week is organized around low-risk movement, sleep, logistics, and emotional steadiness.",
        "Avoid solving every worry with more training.",
        ["Very short easy run", "Optional strides or mobility", "Rest and logistics support"],
        "Minimal load with maximum freshness and low novelty.",
        "For trail and ultra goals, protect feet, quads, travel recovery, and equipment familiarity.",
    ),
    _MicroSpec(
        "micro_041",
        "Post-Competition Reset Week",
        "mezzo_016",
        "Between-Race Recovery Block",
        "between_race_recovery",
        "resets load and complexity after a race",
        "restore enough readiness to make the next between-race decision",
        "The week reduces training while checking soreness, sleep, motivation, and musculoskeletal response.",
        "Avoid assuming a race was just another hard workout.",
        ["Rest day", "Very easy run or walk", "Mobility or gentle aerobic support"],
        "Low load with recovery as the main training input.",
        "Trail races may require extra respect for descents, technical fatigue, heat, and travel.",
    ),
    _MicroSpec(
        "micro_042",
        "Between-Race Bridge Week",
        "mezzo_016",
        "Between-Race Recovery Block",
        "between_race_recovery",
        "rebuilds a small rhythm between events without pretending there is a full block",
        "connect recovery to the next race with minimal useful training",
        "The week restores easy frequency and one small relevant touch only if recovery allows.",
        "Avoid trying to rebuild fitness in a window meant for readiness.",
        ["Easy aerobic run", "Small race-relevant touch", "Recovery day"],
        "Low-to-moderate load depending on race spacing and recovery status.",
        "Use terrain only if it supports confidence for the next event without adding soreness.",
    ),
    _MicroSpec(
        "micro_043",
        "Race Season Rhythm Week",
        "mezzo_017",
        "Race Season Maintenance Block",
        "race_season_maintenance",
        "maintains aerobic rhythm and freshness during race season",
        "hold useful fitness without loading like a development phase",
        "The week keeps easy running consistent and avoids excessive density around competitions.",
        "Avoid filling non-race weeks as if the athlete were not absorbing race stress.",
        ["Easy aerobic run", "Short long run or endurance touch", "Recovery support"],
        "Low-to-moderate repeatable load with freshness protected.",
        "Trail race seasons require accounting for travel, vertical cost, and descent soreness.",
    ),
    _MicroSpec(
        "micro_044",
        "Low-Cost Quality Touch Week",
        "mezzo_017",
        "Race Season Maintenance Block",
        "race_season_maintenance",
        "uses a small controlled stimulus to preserve coordination or intensity familiarity",
        "maintain race-season sharpness without creating a block-level stress",
        "The week includes a brief familiar quality touch surrounded by easy training and recovery.",
        "Avoid chasing workout fitness between races.",
        ["Brief quality touch", "Easy aerobic run", "Recovery day"],
        "Low overall load with a small intensity or coordination signal.",
        "Keep technical and downhill cost low unless the next race specifically requires a confidence touch.",
    ),
    _MicroSpec(
        "micro_045",
        "Race Debrief Learning Week",
        "mezzo_018",
        "Competition Learning Block",
        "competition_learning",
        "turns recent race experience into useful coaching information",
        "learn from competition while physical training cost remains modest",
        "The week pairs easy movement with structured reflection on pacing, fueling, terrain, mindset, and recovery.",
        "Avoid making every lesson an immediate training correction.",
        ["Easy recovery run", "Low-cost rehearsal of one lesson", "Rest or mobility support"],
        "Low-to-moderate load with learning as the primary purpose.",
        "Trail debriefs should include terrain choices, hiking, descents, gear, aid timing, and problem-solving.",
    ),
    _MicroSpec(
        "micro_046",
        "Race Lesson Integration Week",
        "mezzo_018",
        "Competition Learning Block",
        "competition_learning",
        "applies one clear race lesson without overcorrecting",
        "translate race feedback into a manageable training adjustment",
        "The week practices one priority lesson while keeping the rest of training stable.",
        "Avoid changing the whole training model because of one race.",
        ["Targeted lesson practice", "Easy aerobic support run", "Recovery day"],
        "Low-to-moderate load with one targeted adjustment.",
        "Choose the trail or ultra lesson that had the biggest practical consequence.",
    ),
    _MicroSpec(
        "micro_047",
        "Immediate Post-Race Recovery Week",
        "mezzo_019",
        "Post-Race Recovery Block",
        "post_race_recovery",
        "protects healing and basic recovery after a demanding event",
        "recover from race stress before asking for training adaptation",
        "The week prioritizes sleep, nutrition, gentle movement, and honest soreness checks.",
        "Avoid judging the week by fitness maintenance or eagerness to resume.",
        ["Rest", "Walk or very easy movement", "Gentle mobility"],
        "Very low load with recovery as the entire point.",
        "After trail ultras, descents, blisters, travel, and sleep debt may dominate the week.",
    ),
    _MicroSpec(
        "micro_048",
        "Post-Race Return-To-Movement Week",
        "mezzo_019",
        "Post-Race Recovery Block",
        "post_race_recovery",
        "reintroduces easy movement as symptoms and motivation allow",
        "move from passive recovery toward gentle rhythm",
        "The week adds easy running, hiking, or cross-training only when soreness and energy support it.",
        "Avoid using motivation as proof that tissue recovery is complete.",
        ["Very easy run", "Walk or hike", "Rest or mobility day"],
        "Very low-to-low load with flexible frequency.",
        "Keep trails smooth and descents gentle until legs feel normal on stairs and easy running.",
    ),
    _MicroSpec(
        "micro_049",
        "Reduced-Load Absorption Week",
        "mezzo_020",
        "Reduced-Load Adaptation Block",
        "reduced_load_adaptation",
        "lowers training cost so recent stress can be absorbed",
        "preserve rhythm while fatigue settles",
        "The week reduces volume, intensity, density, terrain cost, or strength load while keeping simple routine.",
        "Avoid hiding normal training inside a recovery-labelled week.",
        ["Easy aerobic run", "Rest day", "Mobility or low-impact aerobic support"],
        "Reduced load across the variable most responsible for fatigue.",
        "Lower technicality and descent cost if mechanical fatigue is part of the problem.",
    ),
    _MicroSpec(
        "micro_050",
        "Reduced-Load Readiness Check Week",
        "mezzo_020",
        "Reduced-Load Adaptation Block",
        "reduced_load_adaptation",
        "checks whether the athlete is ready to resume building",
        "make the next progression decision from response rather than impatience",
        "The week uses simple sessions to observe easy-effort feel, soreness, motivation, and recovery.",
        "Avoid adding a hard test to prove readiness.",
        ["Easy run with response check", "Short familiar touch if appropriate", "Rest or mobility day"],
        "Low-to-moderate load with stable, familiar demands.",
        "Use terrain the athlete already tolerates so readiness signals are not confused by novelty.",
    ),
    _MicroSpec(
        "micro_051",
        "Transition Reorientation Week",
        "mezzo_021",
        "Transition Bridge Block",
        "transition_bridge",
        "shifts attention from one training emphasis to the next",
        "avoid abrupt jumps between blocks",
        "The week reduces pressure and introduces the next block's logic in a small, low-risk way.",
        "Avoid starting the next block at full demand before the athlete has reoriented.",
        ["Easy aerobic run", "Small preview of next emphasis", "Recovery support"],
        "Low-to-moderate load with reduced novelty and one preview element.",
        "Trail preview work should be small enough that terrain does not dominate the week.",
    ),
    _MicroSpec(
        "micro_052",
        "Transition Rhythm Week",
        "mezzo_021",
        "Transition Bridge Block",
        "transition_bridge",
        "re-establishes normal weekly rhythm before the next block",
        "enter the next block cleanly and predictably",
        "The week rebuilds enough frequency, easy volume, and routine to make the next block realistic.",
        "Avoid turning a bridge week into a hidden development week.",
        ["Easy aerobic run", "Normal rhythm support run", "Rest or mobility day"],
        "Moderate but controlled easy load with low complexity.",
        "Use familiar terrain and keep vertical or technical load aligned with the next block's starting point.",
    ),
    _MicroSpec(
        "micro_053",
        "Low-Pressure Aerobic Week",
        "mezzo_022",
        "Low-Pressure Aerobic Rhythm Block",
        "low_pressure_aerobic_rhythm",
        "preserves easy aerobic rhythm without race-preparation pressure",
        "keep movement alive while freshness and motivation return",
        "The week uses easy runs or aerobic alternatives with flexible structure and low emotional cost.",
        "Avoid letting off-season easy training become a secret build.",
        ["Easy run", "Optional aerobic alternative", "Rest or mobility day"],
        "Low-to-moderate easy load with flexible scheduling.",
        "Trails can be used for enjoyment if technicality and descent cost remain low.",
    ),
    _MicroSpec(
        "micro_054",
        "Unstructured Aerobic Option Week",
        "mezzo_022",
        "Low-Pressure Aerobic Rhythm Block",
        "low_pressure_aerobic_rhythm",
        "allows flexible easy movement while preserving enough consistency",
        "give the athlete freedom without losing all rhythm",
        "The week defines loose boundaries for easy movement rather than a strict schedule.",
        "Avoid confusing freedom with random overload.",
        ["Flexible easy run", "Hike or low-impact aerobic option", "Rest day"],
        "Low flexible load with guardrails around intensity and total cost.",
        "Outdoor movement is welcome, but adventurous terrain should not create unwanted recovery debt.",
    ),
    _MicroSpec(
        "micro_055",
        "General Strength Foundation Week",
        "mezzo_023",
        "General Strength And Mobility Block",
        "general_strength_mobility",
        "uses general strength and mobility without demanding immediate race transfer",
        "build general durability and movement options in the off-season",
        "The week makes strength or mobility the main support emphasis while running stays easy and secondary.",
        "Avoid overloading strength so much that it compromises future running rhythm.",
        ["General strength session", "Mobility work", "Easy run or aerobic alternative"],
        "Low-to-moderate strength emphasis with supportive aerobic work.",
        "Trail-specific strength is optional; general capacity matters more than exact terrain mimicry here.",
    ),
    _MicroSpec(
        "micro_056",
        "General Mobility Recovery Week",
        "mezzo_023",
        "General Strength And Mobility Block",
        "general_strength_mobility",
        "keeps movement quality alive while reducing load and soreness",
        "restore range, coordination, and freshness",
        "The week uses mobility, easy movement, and very light strength to support recovery.",
        "Avoid turning mobility recovery into a hard gym week.",
        ["Mobility session", "Very easy run or walk", "Light activation"],
        "Low load with restoration and movement quality emphasized.",
        "Gentle hiking or easy trails can help if footing and descent cost are not stressful.",
    ),
    _MicroSpec(
        "micro_057",
        "Movement Variety Exploration Week",
        "mezzo_024",
        "Movement Variety Block",
        "movement_variety",
        "introduces broader movement options at low pressure",
        "restore freshness and general athleticism without disguised training stress",
        "The week uses hiking, cycling, skiing, gym work, games, or other easy movement choices.",
        "Avoid replacing run stress with equally exhausting cross-training stress.",
        ["Movement variety session", "Easy run or hike", "Rest day"],
        "Low-to-moderate mixed load with novelty controlled.",
        "Trail play is useful when it feels refreshing rather than technically or muscularly costly.",
    ),
    _MicroSpec(
        "micro_058",
        "Movement Variety Rhythm Week",
        "mezzo_024",
        "Movement Variety Block",
        "movement_variety",
        "keeps varied movement repeatable instead of random",
        "make off-season variety sustainable across the week",
        "The week gives varied movement a simple rhythm so enjoyment and recovery can coexist.",
        "Avoid stacking many fun activities until the athlete is unexpectedly tired.",
        ["Easy run", "Cross-training or hike", "Mobility or rest day"],
        "Flexible mixed load with predictable recovery opportunities.",
        "Use terrain and activities that leave the athlete fresher, not secretly depleted.",
    ),
    _MicroSpec(
        "micro_059",
        "Aerobic Maintenance Week",
        "mezzo_025",
        "Aerobic Maintenance Block",
        "aerobic_maintenance",
        "holds useful aerobic rhythm with controlled cost",
        "maintain fitness during busy, between-goal, or constrained periods",
        "The week preserves easy frequency and enough duration to keep aerobic rhythm alive.",
        "Avoid letting maintenance drift into either full build training or minimal token sessions.",
        ["Easy aerobic run", "Shorter long run or endurance touch", "Recovery run"],
        "Moderate repeatable easy load with low complexity.",
        "Trail terrain should be familiar and sustainable enough to repeat during constraints.",
    ),
    _MicroSpec(
        "micro_060",
        "Aerobic Maintenance Refresh Week",
        "mezzo_025",
        "Aerobic Maintenance Block",
        "aerobic_maintenance",
        "adds a small freshness or variety dose without becoming development",
        "keep maintenance mentally and physically alive",
        "The week adds a small change in route, duration, or gentle stimulus while total cost stays controlled.",
        "Avoid using refresh as a doorway into a full build phase.",
        ["Easy run with route variety", "Slightly longer easy run", "Rest or mobility day"],
        "Low-to-moderate load with one small refreshing variation.",
        "Use enjoyable terrain if it does not add meaningful soreness or logistical stress.",
    ),
    _MicroSpec(
        "micro_061",
        "Quality Touchpoint Week",
        "mezzo_026",
        "Quality Touchpoint Block",
        "quality_touchpoint",
        "keeps a small familiar quality stimulus in a low-cost week",
        "preserve coordination or intensity familiarity without creating a capacity block",
        "The week includes one short controlled quality touch with easy training around it.",
        "Avoid extending the quality touch until it becomes the main stress of a development block.",
        ["Short quality touch", "Easy aerobic run", "Recovery day"],
        "Low overall load with a brief controlled quality signal.",
        "Choose simple terrain that supports clean execution and low recovery cost.",
    ),
    _MicroSpec(
        "micro_062",
        "Quality Touchpoint Recovery Week",
        "mezzo_026",
        "Quality Touchpoint Block",
        "quality_touchpoint",
        "places recovery emphasis around a small quality touch",
        "keep maintenance sustainable when quality is present",
        "The week protects easy days before and after the quality touch so maintenance does not become chronic fatigue.",
        "Avoid letting one small quality day justify more moderate running on the other days.",
        ["Brief quality touch", "Recovery run", "Rest or mobility support"],
        "Low load with recovery explicitly protecting the quality touch.",
        "Keep trails easy and familiar so technical cost does not magnify the touchpoint.",
    ),
    _MicroSpec(
        "micro_063",
        "Constraint-Friendly Week",
        "mezzo_027",
        "Constraint-Friendly Consistency Block",
        "constraint_friendly_consistency",
        "builds a realistic week around time, travel, work, family, or energy limits",
        "preserve what matters most when a normal template does not fit",
        "The week chooses the few most valuable sessions and removes low-value complexity.",
        "Avoid forcing a normal training week into abnormal constraints.",
        ["Priority easy run", "Short support session", "Optional low-cost aerobic exposure"],
        "Minimum-to-moderate load shaped by real constraints.",
        "Trail sessions should be chosen only if access and recovery cost are realistic.",
    ),
    _MicroSpec(
        "micro_064",
        "Minimum Effective Rhythm Week",
        "mezzo_027",
        "Constraint-Friendly Consistency Block",
        "constraint_friendly_consistency",
        "defines the smallest useful rhythm that keeps training connected",
        "maintain continuity honestly when capacity is limited",
        "The week uses a minimal repeatable structure that protects identity, health, and future restart ease.",
        "Avoid guilt-driven extras that make the minimum unsustainable.",
        ["Short easy run", "Walk or mobility support", "Optional second short exposure"],
        "Very low-to-low load with consistency as the main win.",
        "Use simple routes and low-friction terrain so logistics do not break the week.",
    ),
)


MAINSTREAM_MICRO_CARDS = [_mainstream_micro(spec) for spec in _SPECS]
