from training_cards.cards.micro._philosophy_micro_builder import (
    PhilosophyMicroSpec,
    build_philosophy_micro_cards,
)
from training_cards.philosophy_profiles import SWAP


P = SWAP
L = "SWAP"


_SPECS = (
    PhilosophyMicroSpec("micro_140", "SWAP Supported Recovery Reset Week", "mezzo_062", "SWAP Supported Recovery Reset Block", "supported_recovery_reset", P, L, "The week treats recovery as physical, emotional, and agency-supportive.", "restore health and readiness without shame or pressure", ["Very easy movement", "Rest or walk", "Supportive mobility"], "Very low load with recovery and agency prioritized.", "Trail exposure should feel safe and restorative, not like a test."),
    PhilosophyMicroSpec("micro_141", "SWAP Confidence Anchor Week", "mezzo_063", "SWAP Confidence Re-Entry Block", "confidence_reentry", P, L, "The week anchors re-entry around confidence and repeatability.", "make training feel safe and possible again", ["Short easy run", "Walk or mobility support", "Rest day"], "Low load with confidence as the main success marker.", "Use familiar routes where the athlete can finish feeling capable."),
    PhilosophyMicroSpec("micro_142", "SWAP Confidence Extension Week", "mezzo_063", "SWAP Confidence Re-Entry Block", "confidence_reentry", P, L, "The week extends re-entry only when confidence and recovery are stable.", "grow rhythm without returning to pressure", ["Easy run", "Small optional aerobic exposure", "Recovery support"], "Low-to-moderate load with one confidence-safe progression.", "Trail terrain should build trust, not expose the athlete to avoidable fear or soreness."),
    PhilosophyMicroSpec("micro_143", "SWAP Sustainable Aerobic Rhythm Week", "mezzo_064", "SWAP Sustainable Aerobic Rhythm Block", "sustainable_aerobic_rhythm", P, L, "The week builds aerobic rhythm through consistency, health, and positive response.", "develop durable aerobic work the athlete can keep liking", ["Easy aerobic run", "Long easy run if appropriate", "Recovery run"], "Moderate easy load with sustainability protected.", "Trails can support joy and durability if they do not create hidden overload."),
    PhilosophyMicroSpec("micro_144", "SWAP Health-Protected Aerobic Build Week", "mezzo_064", "SWAP Sustainable Aerobic Rhythm Block", "sustainable_aerobic_rhythm", P, L, "The week builds aerobic work while keeping health and long-term consistency ahead of ambition.", "increase aerobic load without borrowing from future weeks", ["Easy aerobic build run", "Recovery run", "Mobility or strength support"], "Moderate build load with conservative recovery spacing.", "Use vertical or technical terrain only when it supports health and repeatability."),
    PhilosophyMicroSpec("micro_145", "SWAP Adventure Endurance Exposure Week", "mezzo_065", "SWAP Adventure Endurance Block", "adventure_endurance", P, L, "The week uses adventure as purposeful endurance exposure rather than random overload.", "build endurance and confidence through controlled adventure", ["Adventure endurance outing", "Easy support run", "Recovery day"], "Moderate-to-high endurance load with novelty controlled.", "Choose routes that create curiosity and confidence without excessive risk or damage."),
    PhilosophyMicroSpec("micro_146", "SWAP Adventure Endurance Confidence Week", "mezzo_065", "SWAP Adventure Endurance Block", "adventure_endurance", P, L, "The week repeats or shapes adventure work to build confidence.", "make adventure feel repeatable and athlete-owned", ["Familiar adventure route", "Easy aerobic run", "Reflection or recovery support"], "Moderate endurance load with confidence and agency emphasized.", "Terrain should stretch capability without making the athlete feel trapped or overmatched."),
    PhilosophyMicroSpec("micro_147", "SWAP Adventure Recovery Week", "mezzo_065", "SWAP Adventure Endurance Block", "adventure_endurance", P, L, "The week recovers from adventure stress so the block stays sustainable.", "absorb adventure endurance without losing health or enthusiasm", ["Easy run", "Walk or hike", "Rest or mobility"], "Reduced load after higher-novelty endurance work.", "Reduce descents, technicality, and route complexity if the prior adventure carried hidden cost."),
    PhilosophyMicroSpec("micro_148", "SWAP Economy Skill Touch Week", "mezzo_066", "SWAP Economy Speed Skill Support Block", "economy_speed_skill_support", P, L, "The week keeps economy skill alive inside base work.", "support coordination without hijacking aerobic development", ["Short strides", "Easy aerobic run", "Mobility or drills"], "Low load with brief neuromuscular touches.", "Use smooth terrain where quick relaxed running feels safe and playful."),
    PhilosophyMicroSpec("micro_149", "SWAP Speed-Skill Support Week", "mezzo_066", "SWAP Economy Speed Skill Support Block", "economy_speed_skill_support", P, L, "The week adds small speed-skill support while preserving health.", "practice relaxed speed as a skill, not a strain contest", ["Short relaxed speed touch", "Easy run", "Recovery support"], "Low-to-moderate neuromuscular load with easy support.", "Avoid technical footing for speed touches unless it is very familiar and safe."),
    PhilosophyMicroSpec("micro_150", "SWAP Speed Economy Introduction Week", "mezzo_067", "SWAP Speed Economy Development Block", "speed_economy_development", P, L, "The week introduces speed and economy development with relaxed control.", "start speed/economy work without threat or overreach", ["Short speed-economy session", "Easy aerobic run", "Recovery day"], "Moderate neuromuscular load with low total stress.", "Smooth, forgiving terrain helps speed feel coordinated rather than risky."),
    PhilosophyMicroSpec("micro_151", "SWAP Speed Economy Development Week", "mezzo_067", "SWAP Speed Economy Development Block", "speed_economy_development", P, L, "The week develops speed and economy as sustainable performance skills.", "improve coordination and speed reserve without chasing exhaustion", ["Speed-economy workout", "Easy aerobic support", "Recovery run"], "Moderate quality load with strong easy support.", "Keep trail speed work controlled; technical speed belongs only when skill and safety are ready."),
    PhilosophyMicroSpec("micro_152", "SWAP Speed Economy Absorption Week", "mezzo_067", "SWAP Speed Economy Development Block", "speed_economy_development", P, L, "The week absorbs speed/economy work so it improves coordination rather than creating strain.", "let neuromuscular work settle before progressing", ["Easy run", "Short relaxed strides if recovered", "Rest or mobility"], "Reduced quality load with recovery emphasis.", "Avoid downhill speed or technical novelty while legs feel flat or sore."),
    PhilosophyMicroSpec("micro_153", "SWAP Fatigue-Resistance Development Week", "mezzo_068", "SWAP Fatigue Resistance Development Block", "fatigue_resistance_development", P, L, "The week develops fatigue resistance without worshipping exhaustion.", "explore durability while protecting health and response", ["Fatigue-resistance session", "Easy aerobic run", "Recovery support"], "Moderate-to-high targeted load with narrow scope.", "Use terrain that reflects the durability question without piling on unnecessary damage."),
    PhilosophyMicroSpec("micro_154", "SWAP Fatigue-Resistance Response Week", "mezzo_068", "SWAP Fatigue Resistance Development Block", "fatigue_resistance_development", P, L, "The week reduces load to learn from the fatigue-resistance stimulus.", "decide whether the durability work helped or overreached", ["Easy run", "Low-cost endurance support", "Rest or mobility"], "Reduced load with response and health signals prioritized.", "Lower descent and technical cost so fatigue response can be interpreted clearly."),
    PhilosophyMicroSpec("micro_155", "SWAP Confidence Course Exposure Week", "mezzo_069", "SWAP Confidence-Building Course Demands Block", "confidence_course_demands", P, L, "The week introduces course demands in a way that builds confidence.", "prepare the course without making the athlete feel overmatched", ["Confidence-oriented course exposure", "Easy support run", "Recovery day"], "Moderate specific load with psychological safety protected.", "Choose course-like terrain that is challenging enough to teach and safe enough to build trust."),
    PhilosophyMicroSpec("micro_156", "SWAP Confidence Course Integration Week", "mezzo_069", "SWAP Confidence-Building Course Demands Block", "confidence_course_demands", P, L, "The week integrates course demands into normal rhythm while preserving agency.", "make course preparation feel owned and repeatable", ["Course-demand practice", "Easy aerobic support", "Mobility or recovery"], "Moderate-to-high specific load with supportive recovery.", "Use athlete choice where possible: route, gear, hiking strategy, or pacing cue."),
    PhilosophyMicroSpec("micro_157", "SWAP Confidence Course Simulation Week", "mezzo_069", "SWAP Confidence-Building Course Demands Block", "confidence_course_demands", P, L, "The week simulates course demands to build confidence, not fear.", "practice integrated course demands with agency and restraint", ["Confidence-building simulation", "Easy support run", "Recovery day"], "High specific load with surrounding simplicity.", "Simulation should end with useful belief, not proof-by-suffering."),
    PhilosophyMicroSpec("micro_158", "SWAP Agency Execution Choice Week", "mezzo_070", "SWAP Agency Race Execution Practice Block", "agency_race_execution", P, L, "The week gives the athlete meaningful choice in race-execution practice.", "build decision skill rather than only compliance", ["Execution choice practice", "Easy run", "Reflection or recovery support"], "Low-to-moderate load with decision practice emphasized.", "Trail choices may include hiking timing, poles, technical pacing, fueling access, or route problem-solving."),
    PhilosophyMicroSpec("micro_159", "SWAP Agency Rehearsal Week", "mezzo_070", "SWAP Agency Race Execution Practice Block", "agency_race_execution", P, L, "The week rehearses execution while keeping athlete agency central.", "practice race decisions under realistic but bounded stress", ["Agency-centered rehearsal", "Easy support run", "Recovery day"], "Moderate-to-high rehearsal load with clear recovery.", "Let the athlete practice making decisions, not only executing a script."),
    PhilosophyMicroSpec("micro_160", "SWAP Agency Feedback Week", "mezzo_070", "SWAP Agency Race Execution Practice Block", "agency_race_execution", P, L, "The week turns execution feedback into one athlete-owned adjustment.", "improve race decisions without overcorrecting", ["Targeted execution practice", "Easy run", "Recovery support"], "Low-to-moderate load with one feedback focus.", "Trail feedback should become one practical choice the athlete can use next time."),
    PhilosophyMicroSpec("micro_161", "SWAP Whole-Athlete Recovery Week", "mezzo_071", "SWAP Whole-Athlete Between-Race Recovery Block", "whole_athlete_between_race_recovery", P, L, "The week weighs recovery, excitement, identity, and health between races.", "recover without ignoring the athlete's whole context", ["Very easy run", "Rest or walk", "Supportive mobility"], "Low load with whole-athlete readiness prioritized.", "Trail race recovery should include travel, muscle damage, emotions, and motivation, not only soreness."),
    PhilosophyMicroSpec("micro_162", "SWAP Race-Season Health Week", "mezzo_072", "SWAP Race-Season Health And Joy Block", "race_season_health_joy", P, L, "The week protects health during repeated racing.", "keep race season sustainable before chasing extra fitness", ["Easy aerobic run", "Recovery run", "Mobility or strength support"], "Low-to-moderate load with health protection as the main constraint.", "Avoid turning every trail outing into a race-like effort between actual races."),
    PhilosophyMicroSpec("micro_163", "SWAP Race-Season Joy Touch Week", "mezzo_072", "SWAP Race-Season Health And Joy Block", "race_season_health_joy", P, L, "The week includes a small joyful touch that keeps racing emotionally sustainable.", "preserve engagement and freshness through race season", ["Enjoyable easy run", "Short playful quality touch", "Recovery support"], "Low load with one low-cost joy or coordination signal.", "Use terrain that renews motivation without adding meaningful soreness."),
    PhilosophyMicroSpec("micro_164", "SWAP Race-Season Sustainability Week", "mezzo_072", "SWAP Race-Season Health And Joy Block", "race_season_health_joy", P, L, "The week balances race excitement with long-term consistency.", "stay healthy and engaged across repeated events", ["Easy aerobic run", "Small race-relevant touch if recovered", "Rest day"], "Low-to-moderate race-season maintenance load.", "Account for travel, vert, technical fatigue, and emotional load as part of sustainability."),
    PhilosophyMicroSpec("micro_165", "SWAP Off-Season Play Week", "mezzo_073", "SWAP Off-Season Identity And Play Block", "off_season_identity_play", P, L, "The week uses play as a legitimate off-season training structure.", "restore identity and movement joy without hidden pressure", ["Playful movement session", "Easy run or hike", "Rest day"], "Low flexible load with enjoyment and freshness prioritized.", "Trail play is welcome when it does not become covert race preparation."),
    PhilosophyMicroSpec("micro_166", "SWAP Playful Rhythm Week", "mezzo_073", "SWAP Off-Season Identity And Play Block", "off_season_identity_play", P, L, "The week gives playful movement enough rhythm to stay sustainable.", "keep off-season movement repeatable and emotionally light", ["Easy run", "Playful cross-training or hike", "Mobility or rest"], "Low-to-moderate flexible load with recovery opportunities.", "Use terrain and activities that make the athlete want to come back next week."),
)


SWAP_MICRO_CARDS = build_philosophy_micro_cards(_SPECS)
