from .mainstream_endurance.mainstream_easy_run import mainstream_easy_run
from .mainstream_endurance.mainstream_recovery_run import mainstream_recovery_run
from .mainstream_endurance.mainstream_long_run import mainstream_long_run
from .mainstream_endurance.mainstream_progression_run import mainstream_progression_run
from .mainstream_endurance.mainstream_steady_run import mainstream_steady_run
from .mainstream_endurance.mainstream_tempo_run import mainstream_tempo_run
from .mainstream_endurance.mainstream_threshold_intervals import mainstream_threshold_intervals
from .mainstream_endurance.mainstream_aerobic_power_intervals import mainstream_aerobic_power_intervals
from .mainstream_endurance.mainstream_short_hill_repeats import mainstream_short_hill_repeats
from .mainstream_endurance.mainstream_strength_endurance_hills import mainstream_strength_endurance_hills
from .mainstream_endurance.mainstream_strides import mainstream_strides
from .mainstream_endurance.mainstream_race_simulation_run import mainstream_race_simulation_run
from .mainstream_endurance.mainstream_hiking_or_power_hiking_practice import mainstream_hiking_or_power_hiking_practice
from .mainstream_endurance.mainstream_downhill_conditioning_run import mainstream_downhill_conditioning_run
from .mainstream_endurance.mainstream_submaximal_aerobic_benchmark_run import mainstream_submaximal_aerobic_benchmark_run
from .mainstream_endurance.mainstream_easy_aerobic_run import mainstream_easy_aerobic_run
from .mainstream_endurance.mainstream_progressive_endurance_long_run import mainstream_progressive_endurance_long_run
from .mainstream_endurance.mainstream_controlled_quality_intervals import mainstream_controlled_quality_intervals

SESSION_CARDS = [
    mainstream_easy_run,
    mainstream_recovery_run,
    mainstream_long_run,
    mainstream_progression_run,
    mainstream_steady_run,
    mainstream_tempo_run,
    mainstream_threshold_intervals,
    mainstream_aerobic_power_intervals,
    mainstream_short_hill_repeats,
    mainstream_strength_endurance_hills,
    mainstream_strides,
    mainstream_race_simulation_run,
    mainstream_hiking_or_power_hiking_practice,
    mainstream_downhill_conditioning_run,
    mainstream_submaximal_aerobic_benchmark_run,
    mainstream_easy_aerobic_run,
    mainstream_progressive_endurance_long_run,
    mainstream_controlled_quality_intervals,
]
