[theme]
base = "light"
primaryColor = "#4d554b"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f7f7f7"
textColor = "#252525"
linkColor = "#394136"
borderColor = "#d6d6d6"
baseRadius = "10px"
buttonRadius = "6px"
showWidgetBorder = true
