from training_cards.cards.micro._philosophy_micro_builder import (
    PhilosophyMicroSpec,
    build_philosophy_micro_cards,
)
from training_cards.philosophy_profiles import LYDIARD


P = LYDIARD
L = "Lydiard"


_SPECS = (
    PhilosophyMicroSpec("micro_086", "Lydiard Response-Regulated Absorption Week", "mezzo_039", "Lydiard Response-Regulated Reduced-Load Block", "response_regulated_reduced_load", P, L, "The week reduces load according to athlete response rather than a fixed calendar.", "absorb prior work before moving to the next Lydiard layer", ["Easy aerobic run", "Rest or mobility support", "Short familiar stride touch if recovered"], "Reduced aerobic load with response as the progression gate.", "Trail terrain should be familiar and low cost so the coach can read readiness clearly."),
    PhilosophyMicroSpec("micro_087", "Lydiard Sustainable Aerobic Establishment Week", "mezzo_040", "Lydiard Sustainable Aerobic Conditioning Block", "sustainable_aerobic_conditioning", P, L, "The week establishes the greatest aerobic rhythm the athlete can absorb consistently.", "set a sustainable aerobic base before increasing work", ["Easy aerobic run", "Steady aerobic run by feel", "Long aerobic support run"], "Moderate aerobic load held below strain.", "Trail running can support aerobic development if terrain cost does not distort effort judgement."),
    PhilosophyMicroSpec("micro_088", "Lydiard Aerobic Load Build Week", "mezzo_040", "Lydiard Sustainable Aerobic Conditioning Block", "sustainable_aerobic_conditioning", P, L, "The week builds aerobic work while respecting the slowest adapting system.", "increase aerobic conditioning without forcing premature intensity", ["Aerobic run by feel", "Long aerobic run", "Recovery run"], "Moderate-to-high aerobic load with intensity restraint.", "Use time and effort on trails, and protect descents if musculoskeletal response lags behind aerobic confidence."),
    PhilosophyMicroSpec("micro_089", "Lydiard Aerobic Response Hold Week", "mezzo_040", "Lydiard Sustainable Aerobic Conditioning Block", "sustainable_aerobic_conditioning", P, L, "The week holds aerobic work steady when response suggests more building would be premature.", "consolidate aerobic conditioning before another increase", ["Easy aerobic run", "Familiar longer aerobic run", "Recovery support"], "Stable aerobic load with no major progression.", "Keep terrain similar to a recently successful week so response can be interpreted."),
    PhilosophyMicroSpec("micro_090", "Lydiard Long Aerobic Extension Week", "mezzo_041", "Lydiard Long Aerobic Conditioning Block", "long_aerobic_conditioning", P, L, "The week extends long aerobic work inside the base-first sequence.", "develop long aerobic stamina without detaching the long run from the system", ["Long aerobic run", "Easy aerobic support run", "Recovery run"], "Higher single-session aerobic cost with easy surrounding support.", "Trail long runs should strengthen aerobic durability without becoming race-specific simulations too early."),
    PhilosophyMicroSpec("micro_091", "Lydiard Long Aerobic Support Week", "mezzo_041", "Lydiard Long Aerobic Conditioning Block", "long_aerobic_conditioning", P, L, "The week supports long aerobic conditioning through surrounding volume and effort discipline.", "make the long run part of a coherent aerobic week", ["Medium aerobic run", "Long aerobic run", "Easy recovery run"], "Moderate-to-high aerobic emphasis spread through the week.", "Use hills by feel, but avoid turning ordinary aerobic days into hard climbing sessions."),
    PhilosophyMicroSpec("micro_092", "Lydiard Long Aerobic Consolidation Week", "mezzo_041", "Lydiard Long Aerobic Conditioning Block", "long_aerobic_conditioning", P, L, "The week consolidates long aerobic work before adding duration or later layers.", "stabilize endurance so the next phase has a foundation", ["Familiar long aerobic run", "Easy aerobic run", "Rest or mobility support"], "Stable or slightly reduced aerobic load.", "Keep trail demands repeatable and avoid new descent cost during consolidation."),
    PhilosophyMicroSpec("micro_093", "Lydiard Hill Resistance Introduction Week", "mezzo_042", "Lydiard Hill Resistance Development Block", "hill_resistance_development", P, L, "The week introduces hill resistance as a transition from base, not as random hard hill running.", "prepare mechanics and tissue for hill-resistance development", ["Short hill resistance session", "Easy aerobic run", "Mobility or drills"], "Moderate mechanical load with conservative hill dose.", "Choose grades and footing that support rhythm and mechanics rather than maximal strain."),
    PhilosophyMicroSpec("micro_094", "Lydiard Hill Resistance Development Week", "mezzo_042", "Lydiard Hill Resistance Development Block", "hill_resistance_development", P, L, "The week develops hill resistance while preserving aerobic support.", "bridge aerobic base toward stronger mechanics and later faster work", ["Hill resistance session", "Easy aerobic support run", "Long aerobic run if appropriate"], "Moderate-to-high hill-resistance stress with aerobic support.", "Downhill return and technical footing should not dominate the hill-resistance stimulus."),
    PhilosophyMicroSpec("micro_095", "Lydiard Hill Resistance Coordination Week", "mezzo_042", "Lydiard Hill Resistance Development Block", "hill_resistance_development", P, L, "The week emphasizes coordination and resilient mechanics after hill-resistance exposure.", "turn hill strength into smoother movement without overloading the athlete", ["Hill drills or bounding-style support", "Easy aerobic run", "Recovery support"], "Moderate neuromuscular load with careful spacing.", "Use forgiving terrain so coordination is practiced cleanly rather than under technical survival stress."),
    PhilosophyMicroSpec("micro_096", "Lydiard Hill Transition Absorption Week", "mezzo_043", "Lydiard Hill Transition Absorption Block", "hill_transition_absorption", P, L, "The week absorbs hill-transition work before race-preparation layers are added.", "confirm hill resistance has settled before moving forward", ["Easy aerobic run", "Gentle hill touch if recovered", "Rest or mobility support"], "Reduced hill load with aerobic rhythm maintained.", "Reduce descents and steepness if calves, quads, or connective tissue remain loaded."),
    PhilosophyMicroSpec("micro_097", "Lydiard Capacity Integration Week", "mezzo_044", "Lydiard Capacity Integration Block", "capacity_integration", P, L, "The week coordinates already built capacities instead of trying to create new fitness late.", "integrate aerobic, hill, and faster elements into race preparation", ["Integrated quality session", "Easy aerobic support run", "Long aerobic support if appropriate"], "Moderate integrated quality with strong recovery discipline.", "Trail specificity should express prepared capacity, not introduce a brand-new demand."),
    PhilosophyMicroSpec("micro_098", "Lydiard Race-Preparation Coordination Week", "mezzo_044", "Lydiard Capacity Integration Block", "capacity_integration", P, L, "The week organizes race-preparation elements so they complement rather than compete.", "coordinate timing, rhythm, and readiness before peaking", ["Race-preparation touch", "Easy aerobic run", "Recovery day"], "Moderate load with emphasis on timing and coordination.", "Keep technical or vertical specificity familiar enough that it does not derail freshness."),
    PhilosophyMicroSpec("micro_099", "Lydiard Sequence Expression Sharpening Week", "mezzo_045", "Lydiard Sequence Expression Taper Block", "sequence_expression_taper", P, L, "The week uses small sharpening to express completed preparation.", "preserve race feel without chasing missing fitness", ["Small sharpening touch", "Easy aerobic run", "Recovery day"], "Reduced load with a small familiar performance signal.", "Use only terrain that reinforces confidence and rhythm."),
    PhilosophyMicroSpec("micro_100", "Lydiard Freshness Protection Week", "mezzo_045", "Lydiard Sequence Expression Taper Block", "sequence_expression_taper", P, L, "The week protects freshness so the completed sequence can show up on race day.", "avoid forcing missing work during the taper", ["Short easy run", "Brief familiar rhythm touch", "Rest or mobility support"], "Very reduced load with freshness and confidence prioritized.", "Avoid new trail, climb, or descent demands that could hide fatigue in the final week."),
)


LYDIARD_MICRO_CARDS = build_philosophy_micro_cards(_SPECS)
