from .mainstream_endurance.mainstream_return_to_consistency import mainstream_return_to_consistency
from .mainstream_endurance.mainstream_base_development import mainstream_base_development
from .mainstream_endurance.mainstream_build_phase import mainstream_build_phase
from .mainstream_endurance.mainstream_race_specific_preparation import mainstream_race_specific_preparation
from .mainstream_endurance.mainstream_peak_and_taper import mainstream_peak_and_taper
from .mainstream_endurance.mainstream_recovery_and_reset import mainstream_recovery_and_reset
from .mainstream_endurance.mainstream_evidence_informed_development import mainstream_evidence_informed_development

MACRO_CARDS = [
    mainstream_return_to_consistency,
    mainstream_base_development,
    mainstream_build_phase,
    mainstream_race_specific_preparation,
    mainstream_peak_and_taper,
    mainstream_recovery_and_reset,
    mainstream_evidence_informed_development,
]
