from training_cards.cards.micro._philosophy_micro_builder import (
    PhilosophyMicroSpec,
    build_philosophy_micro_cards,
)
from training_cards.philosophy_profiles import SHARMAN_ULTRA


P = SHARMAN_ULTRA
L = "Sharman Ultra"


_SPECS = (
    PhilosophyMicroSpec("micro_167", "Sharman Course Reality Exposure Week", "mezzo_074", "Sharman Course Reality Preparation Block", "course_reality_preparation", P, L, "The week exposes the athlete to course reality in a way that fits actual access and readiness.", "prepare for real course demands without pretending access is unlimited", ["Course-reality exposure run", "Easy support run", "Recovery day"], "Moderate specific load constrained by athlete context.", "Use available terrain creatively while accounting for vertical, footing, descent cost, weather, and travel."),
    PhilosophyMicroSpec("micro_168", "Sharman Course Reality Integration Week", "mezzo_074", "Sharman Course Reality Preparation Block", "course_reality_preparation", P, L, "The week integrates course demands with the athlete's life and training capacity.", "make course preparation practical and repeatable", ["Course-relevant endurance run", "Easy aerobic support", "Gear or hiking practice"], "Moderate-to-high specific load with practical constraints respected.", "If exact terrain is unavailable, use the closest useful substitute without overclaiming specificity."),
    PhilosophyMicroSpec("micro_169", "Sharman Practical Ultra Execution Week", "mezzo_075", "Sharman Practical Ultra Execution Block", "practical_ultra_execution", P, L, "The week practices the practical decisions that shape an ultra finish.", "turn fitness into usable ultra execution", ["Ultra execution practice", "Easy support run", "Recovery day"], "Moderate-to-high execution load with focused practice.", "Include pacing, hiking, aid, gear, and problem-solving demands that match the athlete's likely race."),
    PhilosophyMicroSpec("micro_170", "Sharman Ultra Problem-Solving Rehearsal Week", "mezzo_075", "Sharman Practical Ultra Execution Block", "practical_ultra_execution", P, L, "The week rehearses likely ultra problems before race day.", "practice responding calmly to foreseeable race problems", ["Problem-solving rehearsal", "Easy run", "Recovery support"], "Moderate rehearsal load with one or two problem scenarios.", "Trail problems may include heat, stomach issues, darkness, poles, shoe choice, pacing errors, or aid delays."),
    PhilosophyMicroSpec("micro_171", "Sharman Sustainable Pacing Practice Week", "mezzo_075", "Sharman Practical Ultra Execution Block", "practical_ultra_execution", P, L, "The week practices sustainable pacing choices rather than heroic effort.", "make ultra pacing practical under realistic terrain demands", ["Sustainable pacing session", "Easy aerobic run", "Recovery day"], "Moderate specific load with pacing as the main skill.", "Use climbs, descents, and hiking transitions to practice patience and effort control."),
    PhilosophyMicroSpec("micro_172", "Sharman Fueling-Gear Integration Week", "mezzo_076", "Sharman Fueling Gear Logistics Block", "fueling_gear_logistics", P, L, "The week integrates fueling, gear, and logistics into ordinary training.", "make race-day systems familiar before rehearsal", ["Fueling and gear practice", "Easy run", "Longer endurance support if appropriate"], "Normal-to-moderate load with practical execution complexity.", "Practice carrying, access, clothing, lighting, poles, shoes, and nutrition under realistic but safe conditions."),
    PhilosophyMicroSpec("micro_173", "Sharman Logistics Rehearsal Week", "mezzo_076", "Sharman Fueling Gear Logistics Block", "fueling_gear_logistics", P, L, "The week rehearses logistics under enough stress to reveal problems.", "test race-day systems before consequences are high", ["Logistics rehearsal outing", "Easy support run", "Recovery day"], "Moderate-to-high execution load with surrounding simplicity.", "Use terrain and duration that expose gear and fueling issues without creating an uncontrolled race simulation."),
    PhilosophyMicroSpec("micro_174", "Sharman Context-Aware Recovery Week", "mezzo_077", "Sharman Context-Aware Between-Race Recovery Block", "context_aware_between_race_recovery", P, L, "The week adapts recovery to race cost, life context, and the next event.", "recover according to what the athlete actually needs", ["Rest or walk", "Very easy run", "Mobility or gentle aerobic support"], "Low recovery load shaped by context.", "Trail race recovery should include descents, travel, heat, sleep loss, blisters, and emotional load."),
    PhilosophyMicroSpec("micro_175", "Sharman Next-Race Readiness Week", "mezzo_077", "Sharman Context-Aware Between-Race Recovery Block", "context_aware_between_race_recovery", P, L, "The week rebuilds just enough readiness for the next race.", "connect recovery to the next event without overbuilding", ["Easy readiness run", "Small race-relevant touch", "Recovery support"], "Low-to-moderate load depending on spacing and recovery.", "Use only terrain that improves next-race confidence without adding avoidable soreness."),
    PhilosophyMicroSpec("micro_176", "Sharman Adaptive Race Feedback Week", "mezzo_078", "Sharman Adaptive Race Feedback Block", "adaptive_race_feedback", P, L, "The week turns race feedback into practical coaching information.", "learn what should actually change after a race", ["Easy recovery run", "Targeted low-cost practice", "Rest or mobility"], "Low-to-moderate load with feedback as the main purpose.", "Ultra feedback should include pacing, fueling, gear, hiking, terrain handling, and problem-solving."),
    PhilosophyMicroSpec("micro_177", "Sharman Practical Adjustment Week", "mezzo_078", "Sharman Adaptive Race Feedback Block", "adaptive_race_feedback", P, L, "The week applies one practical adjustment from race feedback.", "make a targeted improvement without rewriting the whole plan", ["Practical adjustment session", "Easy support run", "Recovery day"], "Low-to-moderate targeted load with narrow scope.", "Choose the adjustment that best fits the athlete's next race and real training access."),
)


SHARMAN_MICRO_CARDS = build_philosophy_micro_cards(_SPECS)
