from training_cards.cards.micro._philosophy_micro_builder import (
    PhilosophyMicroSpec,
    build_philosophy_micro_cards,
)
from training_cards.philosophy_profiles import ENDURANCE_80_20


P = ENDURANCE_80_20
L = "80/20"


_SPECS = (
    PhilosophyMicroSpec("micro_065", "80/20 Low-Intensity Baseline Week", "mezzo_029", "80/20 Low-Intensity Volume Block", "low_intensity_volume", P, L, "The week establishes the athlete's current easy-volume baseline while protecting the low-intensity majority.", "confirm repeatable low-intensity volume before building", ["Easy low-intensity run", "Short recovery run", "Optional low-impact aerobic support"], "Low-to-moderate load with strict easy-intensity control.", "Trail running is allowed only when climbing, footing, or descents do not turn the week into hidden hard work."),
    PhilosophyMicroSpec("micro_066", "80/20 Low-Intensity Volume Build Week", "mezzo_029", "80/20 Low-Intensity Volume Block", "low_intensity_volume", P, L, "The week grows volume through easy frequency or duration without letting moderate effort leak into ordinary runs.", "build low-intensity volume while preserving hard/easy contrast", ["Easy low-intensity run", "Long easy run", "Recovery run"], "Moderate easy load with one controlled volume progression.", "Use time and perceived cost on trails because pace and distance can understate climbing or descent load."),
    PhilosophyMicroSpec("micro_067", "80/20 Low-Intensity Absorption Week", "mezzo_029", "80/20 Low-Intensity Volume Block", "low_intensity_volume", P, L, "The week holds or reduces easy load so volume gains can settle without adding intensity.", "absorb low-intensity volume before another build", ["Short easy run", "Recovery run", "Rest or mobility support"], "Stable or reduced easy load with no added quality.", "Keep terrain familiar and lower vertical or technical cost if easy effort stops feeling easy."),
    PhilosophyMicroSpec("micro_068", "80/20 Long-Endurance Distribution Week", "mezzo_030", "80/20 Long Endurance Distribution Block", "long_endurance_distribution", P, L, "The week places long-endurance work inside the 80/20 distribution instead of treating long duration as automatically easy.", "extend endurance while counting duration, climbing, and muscular cost honestly", ["Long low-intensity run", "Easy aerobic support run", "Recovery day"], "Moderate-to-high endurance load with protected low-intensity support.", "Trail duration, steep hiking, and descents may need to be counted as higher-cost work even when breathing stays controlled."),
    PhilosophyMicroSpec("micro_069", "80/20 Long-Endurance Absorption Week", "mezzo_030", "80/20 Long Endurance Distribution Block", "long_endurance_distribution", P, L, "The week simplifies training after long-endurance stress so the distribution remains useful rather than cosmetic.", "absorb long-duration and trail-muscular cost", ["Easy low-intensity run", "Short recovery run", "Rest or mobility support"], "Reduced endurance load with low intensity protected.", "Reduce descent and technical cost when soreness suggests the previous long work was harder than it looked."),
    PhilosophyMicroSpec("micro_070", "80/20 Planned Moderate Introduction Week", "mezzo_031", "80/20 Planned Moderate Work Block", "planned_moderate_work", P, L, "The week introduces moderate work as a deliberate minority stimulus, not an accidental default pace.", "introduce moderate work without grey-zone drift", ["Planned moderate session", "Easy low-intensity run", "Recovery run"], "Moderate quality touch with clear easy support.", "Use climbs carefully because trail grade can push moderate work beyond the planned stimulus."),
    PhilosophyMicroSpec("micro_071", "80/20 Planned Moderate Development Week", "mezzo_031", "80/20 Planned Moderate Work Block", "planned_moderate_work", P, L, "The week develops a bounded moderate stimulus while the rest of training stays clearly easy.", "build deliberate moderate work inside a protected distribution", ["Moderate development session", "Easy aerobic run", "Long easy run if appropriate"], "Moderate quality emphasis with easy volume still dominant.", "Trail race specificity can justify moderate work, but only if the week names and contains the cost."),
    PhilosophyMicroSpec("micro_072", "80/20 Moderate Spillover Control Week", "mezzo_031", "80/20 Planned Moderate Work Block", "planned_moderate_work", P, L, "The week reduces or simplifies moderate work when it starts spreading into too many sessions.", "restore hard/easy contrast after moderate drift", ["Short moderate touch or no quality", "Easy low-intensity runs", "Rest or recovery support"], "Reduced moderate load with easy running restored.", "Choose flatter or less technical routes if terrain is causing easy days to become moderate."),
    PhilosophyMicroSpec("micro_073", "80/20 High-Intensity Quality Week", "mezzo_032", "80/20 High-Intensity Quality Block", "high_intensity_quality", P, L, "The week places a clear high-intensity stimulus in a large base of easy support.", "develop high-intensity quality without sacrificing low-intensity volume", ["High-intensity interval session", "Easy aerobic run", "Recovery run"], "High-quality focal stress with otherwise easy support.", "Trail footing should be safe enough that mechanics, not survival, define the hard stimulus."),
    PhilosophyMicroSpec("micro_074", "80/20 Hard-Easy Protection Week", "mezzo_032", "80/20 High-Intensity Quality Block", "high_intensity_quality", P, L, "The week protects easy days around hard work so the quality stimulus remains distinct.", "preserve hard/easy contrast around high-intensity work", ["High-intensity touch", "Very easy recovery run", "Rest day"], "Low-to-moderate total load with strong recovery spacing.", "Avoid technical descents after hard work when neuromuscular fatigue could create hidden risk."),
    PhilosophyMicroSpec("micro_075", "80/20 High-Intensity Absorption Week", "mezzo_032", "80/20 High-Intensity Quality Block", "high_intensity_quality", P, L, "The week reduces hard work so the athlete can absorb prior intensity before the next stimulus.", "absorb high-intensity work without losing easy rhythm", ["Easy aerobic run", "Short strides if appropriate", "Recovery day"], "Reduced intensity load with easy rhythm maintained.", "Use low-risk terrain until leg snap and easy effort feel normal again."),
    PhilosophyMicroSpec("micro_076", "80/20 Hill-Strength Introduction Week", "mezzo_033", "80/20 Hill Strength Quality Block", "hill_strength_quality", P, L, "The week introduces hill-strength work as a counted quality stress.", "prepare climbing strength without undercounting muscular load", ["Short hill-strength session", "Easy low-intensity run", "Recovery day"], "Moderate muscular load with conservative volume.", "Keep descents controlled because downhill damage can break the week's distribution even if uphill effort is managed."),
    PhilosophyMicroSpec("micro_077", "80/20 Hill-Strength Quality Week", "mezzo_033", "80/20 Hill Strength Quality Block", "hill_strength_quality", P, L, "The week makes hill strength the key quality stimulus and surrounds it with easy support.", "develop hill strength while preserving 80/20 recovery logic", ["Hill-strength quality session", "Easy aerobic support run", "Recovery run"], "High muscular-quality focus with easy volume protected.", "Count steep hiking, technical climbing, and descending as real load, not scenery."),
    PhilosophyMicroSpec("micro_078", "80/20 Hill-Strength Recovery-Accounting Week", "mezzo_033", "80/20 Hill Strength Quality Block", "hill_strength_quality", P, L, "The week reduces hill cost and watches delayed muscular fatigue after quality climbing.", "absorb hill-strength work while accounting for residual cost", ["Easy run", "Gentle hill touch if recovered", "Rest or mobility support"], "Reduced hill and downhill load with recovery priority.", "Lower vertical and avoid long descents if quads or calves remain loaded."),
    PhilosophyMicroSpec("micro_079", "80/20 Distribution-Safe Course Exposure Week", "mezzo_034", "80/20 Distribution-Safe Course Demands Block", "distribution_safe_course_demands", P, L, "The week adds goal-course exposure without letting specificity erase the low-intensity majority.", "practice course demands inside a distribution-safe week", ["Course-relevant exposure run", "Easy low-intensity support run", "Recovery day"], "Moderate specific load with easy support preserved.", "Use terrain specificity deliberately and count steep, technical, or downhill segments as higher cost when needed."),
    PhilosophyMicroSpec("micro_080", "80/20 Race-Counted Reset Week", "mezzo_035", "80/20 Race-Counted Recovery Block", "race_counted_recovery", P, L, "The week treats a race as the hard stimulus before any additional quality is considered.", "recover from competition while preserving honest intensity accounting", ["Rest or very easy run", "Easy aerobic reset", "Mobility or walk"], "Low load because race cost has already supplied intensity.", "Trail races may require extra recovery for descent damage, heat, travel, and technical fatigue."),
    PhilosophyMicroSpec("micro_081", "80/20 Race-Season Easy-Volume Week", "mezzo_036", "80/20 Race-Season Distribution Maintenance Block", "race_season_distribution", P, L, "The week maintains fitness between races mainly through easy volume.", "preserve aerobic rhythm while race stress supplies much of the intensity", ["Easy aerobic run", "Short long run", "Recovery run"], "Low-to-moderate easy volume with sparse quality.", "Keep trails familiar enough that maintenance does not become another race-like stress."),
    PhilosophyMicroSpec("micro_082", "80/20 Sparse Quality Touch Week", "mezzo_036", "80/20 Race-Season Distribution Maintenance Block", "race_season_distribution", P, L, "The week uses one small quality touch when race spacing allows it.", "maintain coordination without crowding race recovery", ["Brief quality touch", "Easy low-intensity run", "Recovery day"], "Low total load with a small controlled quality signal.", "Avoid technical or downhill-heavy quality close to races unless it is essential and familiar."),
    PhilosophyMicroSpec("micro_083", "80/20 Easy-Discipline Maintenance Week", "mezzo_037", "80/20 Easy Discipline Maintenance Block", "easy_discipline_maintenance", P, L, "The week keeps constrained maintenance genuinely easy instead of letting every run become moderately hard.", "maintain useful rhythm through disciplined easy training", ["Easy low-intensity run", "Short recovery run", "Optional mobility support"], "Low-to-moderate load with easy intensity protected.", "Use simple routes when trail variability makes easy discipline harder to maintain."),
    PhilosophyMicroSpec("micro_084", "80/20 Moderate-Drift Correction Week", "mezzo_037", "80/20 Easy Discipline Maintenance Block", "easy_discipline_maintenance", P, L, "The week deliberately resets intensity when constrained training has become too moderate.", "restore easy training habits before adding quality", ["Very easy run", "Rest day", "Short easy aerobic exposure"], "Reduced load with strict intensity reset.", "Avoid climbs or technical routes that make easy effort difficult to control."),
    PhilosophyMicroSpec("micro_085", "80/20 Quality-Touchpoint Protection Week", "mezzo_038", "80/20 Quality Touchpoint Maintenance Block", "quality_touchpoint_maintenance", P, L, "The week protects easy support around a small quality touch.", "keep a quality touch from becoming hidden development", ["Brief quality touch", "Easy low-intensity run", "Recovery day"], "Low total load with one small quality stimulus.", "Use safe, familiar terrain so the touchpoint does not gain extra mechanical cost."),
)


ENDURANCE_80_20_MICRO_CARDS = build_philosophy_micro_cards(_SPECS)
