from training_cards.cards.micro._philosophy_micro_builder import (
    PhilosophyMicroSpec,
    build_philosophy_micro_cards,
)
from training_cards.philosophy_profiles import EVOKE_ENDURANCE


P = EVOKE_ENDURANCE
L = "Evoke"


_SPECS = (
    PhilosophyMicroSpec("micro_123", "Evoke Layer Absorption Week", "mezzo_055", "Evoke Layer Absorption Recovery Block", "layer_absorption_recovery", P, L, "The week absorbs prior mountain, strength, or muscular-endurance layers before more work is added.", "let the previous layer settle before progressing", ["Easy aerobic run", "Rest or mobility support", "Gentle aerobic support"], "Reduced load with recovery matched to the prior layer.", "Terrain should be simple enough that residual muscular fatigue can be read honestly."),
    PhilosophyMicroSpec("micro_124", "Evoke Aerobic Capacity Baseline Week", "mezzo_056", "Evoke Aerobic Capacity Development Block", "aerobic_capacity_development", P, L, "The week establishes aerobic capacity work as the base layer for later mountain demands.", "confirm sustainable aerobic work before building", ["Easy aerobic run", "Long easy aerobic run", "Recovery run"], "Moderate aerobic load with controlled intensity.", "Use trails only when grade and descent do not pull the athlete out of the intended aerobic range."),
    PhilosophyMicroSpec("micro_125", "Evoke Aerobic Capacity Build Week", "mezzo_056", "Evoke Aerobic Capacity Development Block", "aerobic_capacity_development", P, L, "The week builds aerobic capacity without skipping ahead to mountain specificity.", "increase aerobic capacity as the platform for later layers", ["Easy aerobic volume", "Long aerobic run", "Recovery support"], "Moderate-to-high aerobic load with intensity discipline.", "Time and effort are more useful than pace when trails or climbs are included."),
    PhilosophyMicroSpec("micro_126", "Evoke Aerobic Capacity Absorption Week", "mezzo_056", "Evoke Aerobic Capacity Development Block", "aerobic_capacity_development", P, L, "The week consolidates aerobic work so the next layer has a stable base.", "absorb aerobic capacity work before progressing", ["Easy aerobic run", "Short recovery run", "Rest or mobility"], "Reduced or stable aerobic load.", "Keep trail terrain familiar and reduce descent cost if fatigue is lingering."),
    PhilosophyMicroSpec("micro_127", "Evoke Strength Reserve Development Week", "mezzo_057", "Evoke Strength Reserve Support Block", "strength_reserve_support", P, L, "The week develops strength reserve that can later support muscular endurance.", "build strength reserve without replacing aerobic development", ["Strength reserve session", "Easy aerobic run", "Mobility support"], "Moderate strength emphasis with aerobic support protected.", "Trail load may need to decrease if strength work creates leg soreness."),
    PhilosophyMicroSpec("micro_128", "Evoke Strength Reserve Integration Week", "mezzo_057", "Evoke Strength Reserve Support Block", "strength_reserve_support", P, L, "The week integrates strength reserve work into running so it supports later layers.", "connect strength reserve to sustainable mountain training", ["Strength support session", "Easy trail or aerobic run", "Recovery run"], "Moderate support load with careful spacing.", "Use gentle climbs only if they reinforce strength transfer without excess muscular cost."),
    PhilosophyMicroSpec("micro_129", "Evoke Strength Reserve Deload Week", "mezzo_057", "Evoke Strength Reserve Support Block", "strength_reserve_support", P, L, "The week reduces strength load so reserve work can be absorbed.", "maintain strength signal while lowering fatigue", ["Light strength or activation", "Easy aerobic run", "Mobility support"], "Reduced strength load with easy aerobic rhythm.", "Avoid downhill-heavy terrain while strength soreness is resolving."),
    PhilosophyMicroSpec("micro_130", "Evoke Aerobic Threshold Calibration Week", "mezzo_058", "Evoke Aerobic Threshold Control Block", "aerobic_threshold_control", P, L, "The week calibrates aerobic-threshold control before development work grows.", "anchor intensity to the intended aerobic range", ["Aerobic threshold check run", "Easy aerobic run", "Recovery support"], "Moderate controlled load with calibration as the main job.", "Use terrain where effort can be interpreted; steep climbs may distort calibration."),
    PhilosophyMicroSpec("micro_131", "Evoke Aerobic Threshold Development Week", "mezzo_058", "Evoke Aerobic Threshold Control Block", "aerobic_threshold_control", P, L, "The week develops aerobic threshold while preserving the correct intensity ceiling.", "raise aerobic capacity without drifting too hard", ["Aerobic threshold development session", "Easy aerobic run", "Long aerobic support"], "Moderate quality load with controlled intensity.", "Trail effort should be governed by breathing, effort, and recovery rather than pace."),
    PhilosophyMicroSpec("micro_132", "Evoke Aerobic Threshold Drift Check Week", "mezzo_058", "Evoke Aerobic Threshold Control Block", "aerobic_threshold_control", P, L, "The week simplifies training to catch aerobic drift, fatigue, or intensity creep.", "restore control when aerobic work is becoming too costly", ["Controlled aerobic run", "Easy run", "Recovery day"], "Reduced or stable aerobic load with intensity-control emphasis.", "Use less variable terrain if trails make intensity drift hard to detect."),
    PhilosophyMicroSpec("micro_133", "Evoke Uphill Muscular-Endurance Introduction Week", "mezzo_059", "Evoke Uphill Muscular Endurance Block", "uphill_muscular_endurance", P, L, "The week introduces uphill muscular endurance only after aerobic and strength prerequisites are credible.", "prepare the athlete for specific uphill force demands", ["Short uphill ME session", "Easy aerobic run", "Recovery day"], "Moderate muscular load with conservative uphill dose.", "Choose uphill terrain that creates force demand without dangerous descent cost."),
    PhilosophyMicroSpec("micro_134", "Evoke Uphill Muscular-Endurance Development Week", "mezzo_059", "Evoke Uphill Muscular Endurance Block", "uphill_muscular_endurance", P, L, "The week develops uphill muscular endurance as the defining stress.", "build sustained uphill force capacity for mountain objectives", ["Uphill muscular-endurance session", "Easy aerobic support run", "Recovery support"], "High muscular-specific load with other stresses constrained.", "Track grade, duration, footing, poles, load, and descents as separate cost variables."),
    PhilosophyMicroSpec("micro_135", "Evoke Uphill Muscular-Endurance Recovery Week", "mezzo_059", "Evoke Uphill Muscular Endurance Block", "uphill_muscular_endurance", P, L, "The week reduces uphill muscular demand so adaptation can occur.", "recover from ME stress before adding more", ["Easy aerobic run", "Gentle hike", "Mobility or rest"], "Reduced muscular load with aerobic rhythm protected.", "Avoid steep descents and technical fatigue until legs feel normal again."),
    PhilosophyMicroSpec("micro_136", "Evoke Muscular-Endurance Absorption Week", "mezzo_060", "Evoke Muscular Endurance Absorption Block", "muscular_endurance_absorption", P, L, "The week lets prior muscular-endurance work become usable capacity.", "absorb the ME layer instead of stacking more stress", ["Easy aerobic run", "Low-cost hike", "Rest or mobility"], "Reduced specific load with recovery as the main adaptation support.", "Use gentle terrain and avoid testing strength endurance while soreness is still present."),
    PhilosophyMicroSpec("micro_137", "Evoke Objective Utilisation Integration Week", "mezzo_061", "Evoke Objective Utilisation Block", "objective_utilisation", P, L, "The week begins using developed capacity in objective-relevant combinations.", "integrate capacity into practical mountain-objective preparation", ["Objective-relevant endurance session", "Easy support run", "Recovery day"], "Moderate-to-high specific load using existing capacity.", "Combine terrain demands only when the athlete already owns the underlying layers."),
    PhilosophyMicroSpec("micro_138", "Evoke Objective Simulation Week", "mezzo_061", "Evoke Objective Utilisation Block", "objective_utilisation", P, L, "The week simulates the objective enough to practice utilisation, not create new capacity.", "rehearse objective demands from an already prepared base", ["Objective simulation outing", "Fueling or gear practice", "Recovery support"], "High specific load with surrounding simplicity.", "Simulation should respect weather, altitude, terrain, remoteness, and descent cost."),
    PhilosophyMicroSpec("micro_139", "Evoke Objective Readiness Week", "mezzo_061", "Evoke Objective Utilisation Block", "objective_utilisation", P, L, "The week protects readiness after objective-specific work.", "arrive ready to use capacity rather than fatigued from proving it", ["Short objective cue session", "Easy aerobic run", "Rest or mobility"], "Reduced specific load with readiness prioritized.", "Avoid final-week mountain novelty or long descents that could hide residual damage."),
)


EVOKE_MICRO_CARDS = build_philosophy_micro_cards(_SPECS)
