from training_cards.cards.micro._philosophy_micro_builder import (
    PhilosophyMicroSpec,
    build_philosophy_micro_cards,
)
from training_cards.philosophy_profiles import CTS


P = CTS
L = "CTS"


_SPECS = (
    PhilosophyMicroSpec("micro_101", "CTS Repeatable Workload Baseline Week", "mezzo_046", "CTS Repeatable Workload Foundation Block", "repeatable_workload_foundation", P, L, "The week identifies workload the athlete can repeat, not merely complete once.", "establish repeatable workload before sharper demands", ["Easy aerobic run", "Longer easy run if already stable", "Recovery support"], "Moderate controlled workload with repeatability as the gate.", "Trail load should include time, vertical, descent damage, and technical cost rather than distance alone."),
    PhilosophyMicroSpec("micro_102", "CTS Workload Extension Week", "mezzo_046", "CTS Repeatable Workload Foundation Block", "repeatable_workload_foundation", P, L, "The week extends workload only where recovery and life constraints support it.", "build durable workload that can survive real life", ["Easy aerobic run", "Long-run extension", "Recovery run"], "Moderate-to-high aerobic workload with one extension variable.", "Use terrain that reflects likely goals but does not make repeatability impossible."),
    PhilosophyMicroSpec("micro_103", "CTS Workload Cost Check Week", "mezzo_046", "CTS Repeatable Workload Foundation Block", "repeatable_workload_foundation", P, L, "The week holds or reduces workload to understand the cost of recent training.", "verify workload is useful before increasing it", ["Easy aerobic run", "Low-cost endurance support", "Rest or mobility"], "Stable or reduced workload with response monitoring.", "Simplify trail terrain when soreness or life stress makes true cost unclear."),
    PhilosophyMicroSpec("micro_104", "CTS Long-Run Durability Build Week", "mezzo_047", "CTS Long-Run Durability Block", "long_run_durability", P, L, "The week builds long-run durability for real event demands.", "increase long-run tolerance that matters for the goal", ["Long durability run", "Easy support run", "Recovery day"], "High single-session endurance cost with supportive weekly load.", "Target the relevant ultra demand: duration, vertical, descent, heat, footing, hiking, or fueling."),
    PhilosophyMicroSpec("micro_105", "CTS Terrain-Durability Week", "mezzo_047", "CTS Long-Run Durability Block", "long_run_durability", P, L, "The week shifts durability work toward terrain-specific cost.", "prepare the body for the terrain that will limit performance", ["Terrain-specific endurance run", "Easy aerobic run", "Mobility or strength support"], "Moderate-to-high terrain load with one dominant limiter.", "Track downhill and technical cost separately because they can outlast aerobic fatigue."),
    PhilosophyMicroSpec("micro_106", "CTS Durability Absorption Week", "mezzo_047", "CTS Long-Run Durability Block", "long_run_durability", P, L, "The week reduces load so long-run durability work can consolidate.", "absorb long-run and terrain stress before the next build", ["Easy run", "Short endurance support", "Rest or mobility"], "Reduced endurance and terrain load.", "Lower descent and technical exposure if muscle damage is still present."),
    PhilosophyMicroSpec("micro_107", "CTS Limiter-Focused Quality Week", "mezzo_048", "CTS Limiter-Focused Quality Block", "limiter_focused_quality", P, L, "The week targets one meaningful performance limiter instead of adding quality generically.", "train the limiter with clear trade-offs", ["Limiter-focused quality session", "Easy support run", "Recovery run"], "Moderate-to-high focused quality with other stresses constrained.", "Choose terrain only when it directly serves the limiter rather than making the session impressive."),
    PhilosophyMicroSpec("micro_108", "CTS Limiter Response Week", "mezzo_048", "CTS Limiter-Focused Quality Block", "limiter_focused_quality", P, L, "The week checks whether limiter work is producing adaptation or excess cost.", "adapt the next quality choice from response", ["Reduced quality touch", "Easy aerobic run", "Recovery support"], "Reduced or stable quality load with response emphasis.", "Use familiar terrain so limiter response is not confused by new mechanical stress."),
    PhilosophyMicroSpec("micro_109", "CTS Ultra Strength-Endurance Introduction Week", "mezzo_049", "CTS Ultra Strength-Endurance Limiter Block", "ultra_strength_endurance_limiter", P, L, "The week introduces strength-endurance work only when it solves an ultra limiter.", "prepare muscular durability for relevant ultra demands", ["Short uphill strength-endurance session", "Easy run", "Strength or mobility support"], "Moderate muscular load with conservative exposure.", "Grade, footing, poles, hiking, and descent return should match the limiter being addressed."),
    PhilosophyMicroSpec("micro_110", "CTS Ultra Strength-Endurance Development Week", "mezzo_049", "CTS Ultra Strength-Endurance Limiter Block", "ultra_strength_endurance_limiter", P, L, "The week develops the specific muscular-endurance limiter with controlled support.", "improve climbing or terrain fatigue resistance for the goal event", ["Uphill strength-endurance session", "Easy aerobic support", "Recovery day"], "High muscular-specific load with simplified surrounding training.", "Avoid increasing steepness, duration, load, and technical descent in the same week."),
    PhilosophyMicroSpec("micro_111", "CTS Muscular-Cost Absorption Week", "mezzo_049", "CTS Ultra Strength-Endurance Limiter Block", "ultra_strength_endurance_limiter", P, L, "The week absorbs muscular-endurance work before another specific dose.", "let muscular stress become usable adaptation", ["Easy aerobic run", "Gentle hike", "Mobility or rest"], "Reduced muscular and downhill cost.", "Keep trail terrain gentle if quads, calves, or connective tissue remain loaded."),
    PhilosophyMicroSpec("micro_112", "CTS Event-Demands Exposure Week", "mezzo_050", "CTS Event Demands Block", "event_demands", P, L, "The week exposes the athlete to one meaningful event demand.", "prepare for the demand most likely to matter", ["Event-demand exposure run", "Easy support run", "Recovery day"], "Moderate specific load with one demand emphasized.", "Select the consequential course variable rather than copying the race broadly."),
    PhilosophyMicroSpec("micro_113", "CTS Event-Demands Integration Week", "mezzo_050", "CTS Event Demands Block", "event_demands", P, L, "The week integrates event-specific work into the broader training rhythm.", "turn event demands into repeatable preparation", ["Event-specific training run", "Easy aerobic run", "Support or recovery session"], "Moderate-to-high specific load balanced by easy support.", "Account for vertical, descent, heat, altitude, aid spacing, and technicality as real load."),
    PhilosophyMicroSpec("micro_114", "CTS Race-Execution Planning Week", "mezzo_051", "CTS Race Execution Rehearsal Block", "race_execution_rehearsal", P, L, "The week structures low-cost practice around a clear execution plan.", "prepare pacing, gear, aid, and decision routines before rehearsal", ["Easy run with execution cues", "Gear or aid-flow practice", "Recovery run"], "Normal-to-moderate load with execution complexity introduced.", "Trail execution may include hiking transitions, poles, technical pacing, or aid-station timing."),
    PhilosophyMicroSpec("micro_115", "CTS Race-Execution Rehearsal Week", "mezzo_051", "CTS Race Execution Rehearsal Block", "race_execution_rehearsal", P, L, "The week rehearses race execution in a bounded, learnable way.", "practice coordinated race-day decisions under relevant stress", ["Race-execution rehearsal", "Easy support run", "Recovery day"], "Moderate-to-high rehearsal load with other stresses reduced.", "Use representative terrain when possible, but do not let rehearsal become an uncontrolled race."),
    PhilosophyMicroSpec("micro_116", "CTS Execution Adjustment Week", "mezzo_051", "CTS Race Execution Rehearsal Block", "race_execution_rehearsal", P, L, "The week applies one execution adjustment after rehearsal.", "improve race strategy without changing everything at once", ["Targeted execution practice", "Easy aerobic run", "Recovery support"], "Low-to-moderate load with one practical adjustment.", "Focus on the trail or ultra decision that would most change race outcome."),
    PhilosophyMicroSpec("micro_117", "CTS Fueling Strategy Integration Week", "mezzo_052", "CTS Fueling And Hydration Strategy Block", "fueling_hydration_strategy", P, L, "The week integrates planned fueling into ordinary training.", "make nutrition strategy practical before race rehearsal", ["Easy run with fueling plan", "Long run intake practice", "Hydration check"], "Normal training load with intentional fueling practice.", "Heat, altitude, aid spacing, pack access, and climb duration may shape the strategy."),
    PhilosophyMicroSpec("micro_118", "CTS Fueling Strategy Rehearsal Week", "mezzo_052", "CTS Fueling And Hydration Strategy Block", "fueling_hydration_strategy", P, L, "The week rehearses fueling and hydration under goal-relevant stress.", "test nutrition strategy in conditions that teach useful lessons", ["Long fueling rehearsal", "Race-relevant hydration practice", "Easy recovery run"], "Moderate-to-high execution load with planned nutrition stress.", "Practice carrying, timing, products, and aid access under terrain and heat that resemble the goal."),
    PhilosophyMicroSpec("micro_119", "CTS Fueling Problem-Solving Week", "mezzo_052", "CTS Fueling And Hydration Strategy Block", "fueling_hydration_strategy", P, L, "The week simplifies training so fueling problems can be isolated and solved.", "improve nutrition reliability before bigger rehearsal", ["Controlled fueling test", "Easy run", "Recovery support"], "Low-to-moderate physical load with focused nutrition troubleshooting.", "Use enough terrain realism to reproduce the issue without creating a second problem."),
    PhilosophyMicroSpec("micro_120", "CTS Race-Stress Recovery Week", "mezzo_053", "CTS Race Stress Recovery Block", "race_stress_recovery", P, L, "The week responds to the specific stress profile of the last race.", "recover according to what the race actually cost", ["Rest or walk", "Very easy run", "Mobility or gentle aerobic support"], "Low load shaped by race cost.", "Trail ultras may require recovery from descents, heat, altitude, blisters, sleep loss, and travel."),
    PhilosophyMicroSpec("micro_121", "CTS Between-Event Decision Week", "mezzo_054", "CTS Between-Event Adjustment Block", "between_event_adjustment", P, L, "The week uses race feedback and readiness to choose the next between-event emphasis.", "decide whether to recover, maintain, or adjust toward the next event", ["Easy readiness run", "Small targeted touch if appropriate", "Recovery support"], "Low-to-moderate load while the next emphasis is selected.", "Terrain should support clear feedback rather than add noise."),
    PhilosophyMicroSpec("micro_122", "CTS Between-Event Targeted Adjustment Week", "mezzo_054", "CTS Between-Event Adjustment Block", "between_event_adjustment", P, L, "The week makes one targeted adjustment for the next event.", "improve the highest-value limiter before the next race", ["Targeted adjustment session", "Easy support run", "Recovery day"], "Moderate targeted load with narrow scope.", "Choose the adjustment with the highest practical payoff for the next trail or ultra demand."),
)


CTS_MICRO_CARDS = build_philosophy_micro_cards(_SPECS)
